import { createContext, useCallback, useContext, useMemo, useReducer, type ReactNode } from 'react'

import {
  explorerIndex,
  getExplorerChildren,
  getExplorerNode,
  type ExplorerFolderNode,
  type ExplorerIndexEntry,
  type ExplorerNode,
} from '@/data/algoviz-explorer'

const { root } = explorerIndex

/**
 * Display order for root folders on the desktop and in the Start menu.
 * Folders not in this list appear at the end in discovery order.
 */
const ROOT_FOLDER_ORDER = [
  'folder:0-fundamentals',
  'folder:0-languages-ecosystems',
  // Alias shortcut generated by algoviz-explorer.ts — a curated subset of
  // "Languages & Ecosystems" surfaced as its own desktop folder.
  'alias:languages-and-frameworks:folder:languages-and-frameworks',
  'folder:1-core-data-structures',
  'folder:2-core-algorithms',
  'folder:3-algorithmic-paradigms',
  'folder:0-cs-problems-theory',
  'folder:4-advanced-topics',
  'folder:5-applied-domains',
]

function sortRootFolders<T extends { id: string }>(folders: T[]): T[] {
  const lookup = new Map(folders.map((node) => [node.id, node]))
  const ordered = ROOT_FOLDER_ORDER.map((id) => lookup.get(id)).filter(
    (node): node is NonNullable<typeof node> => Boolean(node),
  )
  const rest = folders.filter((node) => !ROOT_FOLDER_ORDER.includes(node.id))
  return [...ordered, ...rest]
}

interface WindowStateBase {
  id: string
  title: string
  isMinimized: boolean
  zIndex: number
  initialPosition: { x: number; y: number }
}

export interface FolderWindowState extends WindowStateBase {
  kind: 'folder'
  nodeId: string
  path: string[]
  history: string[][]
  forwardHistory: string[][]
}

export interface TopicWindowState extends WindowStateBase {
  kind: 'topic'
  route: string
  initialSize: { width: number; height: number }
}

export type WindowState = FolderWindowState | TopicWindowState

export const isFolderWindow = (win: WindowState): win is FolderWindowState => win.kind === 'folder'

export const isTopicWindow = (win: WindowState): win is TopicWindowState => win.kind === 'topic'

const TOPIC_WINDOW_SIZE = { width: 980, height: 640 }

interface ManagerState {
  windows: WindowState[]
  activeWindowId?: string
  zCounter: number
  nextOffset: number
}

export const INITIAL_STATE: ManagerState = {
  windows: [],
  zCounter: 10,
  nextOffset: 0,
}

type ManagerAction =
  | { type: 'OPEN_FOLDER_WINDOW'; nodeId: string }
  | { type: 'OPEN_TOPIC_WINDOW'; route: string; title: string }
  | { type: 'FOCUS_WINDOW'; windowId: string }
  | { type: 'CLOSE_WINDOW'; windowId: string }
  | { type: 'MINIMIZE_WINDOW'; windowId: string }
  | { type: 'RESTORE_WINDOW'; windowId: string }
  | { type: 'NAVIGATE_TO_CHILD'; windowId: string; nodeId: string }
  | { type: 'NAVIGATE_BACK'; windowId: string }
  | { type: 'NAVIGATE_FORWARD'; windowId: string }
  | { type: 'NAVIGATE_UP'; windowId: string }

const createWindowId = () => {
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
    return crypto.randomUUID()
  }

  return `win-${Math.random().toString(36).slice(2)}`
}

const makePosition = (offset: number) => ({
  x: 160 + offset,
  y: 120 + offset,
})

const bumpZIndex = (state: ManagerState): [ManagerState, number] => {
  const nextZ = state.zCounter + 1
  return [{ ...state, zCounter: nextZ }, nextZ]
}

const withFocusedWindow = (state: ManagerState, windowId: string): ManagerState => {
  const [, newZ] = bumpZIndex(state)
  return {
    ...state,
    windows: state.windows.map((win) =>
      win.id === windowId
        ? {
            ...win,
            zIndex: newZ,
          }
        : win,
    ),
    activeWindowId: windowId,
    zCounter: newZ,
  }
}

export const reduceManager = (state: ManagerState, action: ManagerAction): ManagerState => {
  switch (action.type) {
    case 'OPEN_FOLDER_WINDOW': {
      const entry = getExplorerNode(action.nodeId)
      if (!entry || entry.node.kind !== 'folder') {
        return state
      }

      const existing = state.windows.find(
        (win) => isFolderWindow(win) && win.nodeId === action.nodeId,
      )
      if (existing) {
        const baseState = existing.isMinimized
          ? {
              ...state,
              windows: state.windows.map((win) =>
                win.id === existing.id
                  ? {
                      ...win,
                      isMinimized: false,
                    }
                  : win,
              ),
            }
          : state

        return withFocusedWindow(baseState, existing.id)
      }

      const windowId = createWindowId()
      const offset = (state.nextOffset + 24) % 72
      const [nextState, zIndex] = bumpZIndex({ ...state, nextOffset: offset })
      const pathIds = entry.pathEntries.map((node) => node.id)
      const initialHistory = pathIds.length > 1 ? [pathIds.slice(0, -1)] : []

      const newWindow: FolderWindowState = {
        id: windowId,
        kind: 'folder',
        nodeId: action.nodeId,
        title: entry.node.name,
        isMinimized: false,
        zIndex,
        path: pathIds,
        history: initialHistory,
        forwardHistory: [],
        initialPosition: makePosition(offset),
      }

      return {
        ...nextState,
        windows: [...nextState.windows, newWindow],
        activeWindowId: windowId,
      }
    }

    case 'OPEN_TOPIC_WINDOW': {
      const existingTopic = state.windows.find(isTopicWindow)
      if (existingTopic) {
        const baseState = {
          ...state,
          windows: state.windows.map((win) =>
            win.id === existingTopic.id
              ? {
                  ...win,
                  route: action.route,
                  title: action.title,
                  isMinimized: false,
                }
              : win,
          ),
        }

        return withFocusedWindow(baseState, existingTopic.id)
      }

      const windowId = createWindowId()
      const offset = (state.nextOffset + 24) % 72
      const [nextState, zIndex] = bumpZIndex({ ...state, nextOffset: offset })
      const newWindow: TopicWindowState = {
        id: windowId,
        kind: 'topic',
        route: action.route,
        title: action.title,
        isMinimized: false,
        zIndex,
        initialPosition: makePosition(offset),
        initialSize: TOPIC_WINDOW_SIZE,
      }

      return {
        ...nextState,
        windows: [...nextState.windows, newWindow],
        activeWindowId: windowId,
      }
    }

    case 'FOCUS_WINDOW':
      return withFocusedWindow(state, action.windowId)

    case 'CLOSE_WINDOW':
      return {
        ...state,
        windows: state.windows.filter((win) => win.id !== action.windowId),
        activeWindowId: state.activeWindowId === action.windowId ? undefined : state.activeWindowId,
      }

    case 'MINIMIZE_WINDOW':
      return {
        ...state,
        windows: state.windows.map((win) =>
          win.id === action.windowId
            ? {
                ...win,
                isMinimized: true,
              }
            : win,
        ),
        activeWindowId: state.activeWindowId === action.windowId ? undefined : state.activeWindowId,
      }

    case 'RESTORE_WINDOW':
      return withFocusedWindow(
        {
          ...state,
          windows: state.windows.map((win) =>
            win.id === action.windowId
              ? {
                  ...win,
                  isMinimized: false,
                }
              : win,
          ),
        },
        action.windowId,
      )

    case 'NAVIGATE_TO_CHILD': {
      const entry = getExplorerNode(action.nodeId)
      if (!entry || entry.node.kind !== 'folder') {
        return state
      }

      return {
        ...state,
        windows: state.windows.map((win) => {
          if (win.id !== action.windowId || !isFolderWindow(win)) {
            return win
          }

          const currentPath = [...win.path]
          return {
            ...win,
            nodeId: action.nodeId,
            title: entry.node.name,
            path: entry.pathEntries.map((node) => node.id),
            history: [...win.history, currentPath],
            forwardHistory: [],
          }
        }),
      }
    }

    case 'NAVIGATE_BACK':
      return {
        ...state,
        windows: state.windows.map((win) => {
          if (win.id !== action.windowId || !isFolderWindow(win)) {
            return win
          }

          const history = [...win.history]
          const previous = history.pop()
          if (!previous) {
            return win
          }

          const targetId = previous[previous.length - 1]
          if (!targetId) {
            return win
          }

          const entry = getExplorerNode(targetId)
          if (!entry) {
            return win
          }

          return {
            ...win,
            nodeId: targetId,
            title: entry.node.name,
            path: [...previous],
            history,
            forwardHistory: [...win.forwardHistory, [...win.path]],
          }
        }),
      }

    case 'NAVIGATE_FORWARD':
      return {
        ...state,
        windows: state.windows.map((win) => {
          if (win.id !== action.windowId || !isFolderWindow(win)) {
            return win
          }

          const forwardHistory = [...win.forwardHistory]
          const next = forwardHistory.pop()
          if (!next) {
            return win
          }

          const targetId = next[next.length - 1]
          if (!targetId) {
            return win
          }

          const entry = getExplorerNode(targetId)
          if (!entry) {
            return win
          }

          return {
            ...win,
            nodeId: targetId,
            title: entry.node.name,
            path: [...next],
            history: [...win.history, [...win.path]],
            forwardHistory,
          }
        }),
      }

    case 'NAVIGATE_UP':
      return {
        ...state,
        windows: state.windows.map((win) => {
          if (win.id !== action.windowId || !isFolderWindow(win) || win.path.length <= 1) {
            return win
          }

          const parentPath = win.path.slice(0, -1)
          const targetId = parentPath[parentPath.length - 1]
          if (!targetId) {
            return win
          }

          const entry = getExplorerNode(targetId)
          if (!entry) {
            return win
          }

          return {
            ...win,
            nodeId: targetId,
            title: entry.node.name,
            path: parentPath,
            history: [...win.history, [...win.path]],
            forwardHistory: [],
          }
        }),
      }

    default:
      return state
  }
}

interface WindowManagerValue {
  windows: WindowState[]
  activeWindowId?: string
  orderedRootFolders: ExplorerFolderNode[]
  focusWindow: (windowId: string) => void
  closeWindow: (windowId: string) => void
  minimizeWindow: (windowId: string) => void
  restoreWindow: (windowId: string) => void
  toggleMinimize: (windowId: string) => void
  openFolderWindow: (nodeId: string) => void
  openTopicWindow: (route: string, title: string) => void
  navigateToChild: (windowId: string, nodeId: string) => void
  navigateBack: (windowId: string) => void
  navigateForward: (windowId: string) => void
  navigateUp: (windowId: string) => void
  getPathEntries: (path: string[]) => ExplorerIndexEntry[]
  getChildren: (nodeId: string) => ExplorerNode[]
}

const Win96WindowManagerContext = createContext<WindowManagerValue | null>(null)

export interface Win96WindowManagerProviderProps {
  children: ReactNode
}

export const Win96WindowManagerProvider = ({ children }: Win96WindowManagerProviderProps) => {
  const [state, dispatch] = useReducer(reduceManager, INITIAL_STATE)

  const orderedRootFolders = useMemo(
    () =>
      sortRootFolders(
        (root.children ?? []).filter((node): node is ExplorerFolderNode => node.kind === 'folder'),
      ),
    [],
  )

  const focusWindow = useCallback((windowId: string) => {
    dispatch({ type: 'FOCUS_WINDOW', windowId })
  }, [])

  const closeWindow = useCallback((windowId: string) => {
    dispatch({ type: 'CLOSE_WINDOW', windowId })
  }, [])

  const minimizeWindow = useCallback((windowId: string) => {
    dispatch({ type: 'MINIMIZE_WINDOW', windowId })
  }, [])

  const restoreWindow = useCallback((windowId: string) => {
    dispatch({ type: 'RESTORE_WINDOW', windowId })
  }, [])

  const toggleMinimize = useCallback(
    (windowId: string) => {
      const target = state.windows.find((win) => win.id === windowId)
      if (!target) {
        return
      }

      if (target.isMinimized) {
        dispatch({ type: 'RESTORE_WINDOW', windowId })
      } else {
        dispatch({ type: 'MINIMIZE_WINDOW', windowId })
      }
    },
    [state.windows],
  )

  const openFolderWindow = useCallback((nodeId: string) => {
    dispatch({ type: 'OPEN_FOLDER_WINDOW', nodeId })
  }, [])

  const openTopicWindow = useCallback((route: string, title: string) => {
    dispatch({ type: 'OPEN_TOPIC_WINDOW', route, title })
  }, [])

  const navigateToChild = useCallback((windowId: string, nodeId: string) => {
    dispatch({ type: 'NAVIGATE_TO_CHILD', windowId, nodeId })
  }, [])

  const navigateBack = useCallback((windowId: string) => {
    dispatch({ type: 'NAVIGATE_BACK', windowId })
  }, [])

  const navigateForward = useCallback((windowId: string) => {
    dispatch({ type: 'NAVIGATE_FORWARD', windowId })
  }, [])

  const navigateUp = useCallback((windowId: string) => {
    dispatch({ type: 'NAVIGATE_UP', windowId })
  }, [])

  const getChildren = useCallback((nodeId: string) => getExplorerChildren(nodeId), [])

  const getPathEntries = useCallback((path: string[]) => {
    return path
      .map((id) => explorerIndex.map.get(id))
      .filter((entry): entry is ExplorerIndexEntry => Boolean(entry))
  }, [])

  const value = useMemo<WindowManagerValue>(
    () => ({
      windows: state.windows,
      activeWindowId: state.activeWindowId,
      orderedRootFolders,
      focusWindow,
      closeWindow,
      minimizeWindow,
      restoreWindow,
      toggleMinimize,
      openFolderWindow,
      openTopicWindow,
      navigateToChild,
      navigateBack,
      navigateForward,
      navigateUp,
      getChildren,
      getPathEntries,
    }),
    [
      state.windows,
      state.activeWindowId,
      orderedRootFolders,
      focusWindow,
      closeWindow,
      minimizeWindow,
      restoreWindow,
      toggleMinimize,
      openFolderWindow,
      openTopicWindow,
      navigateToChild,
      navigateBack,
      navigateForward,
      navigateUp,
      getChildren,
      getPathEntries,
    ],
  )

  return (
    <Win96WindowManagerContext.Provider value={value}>
      {children}
    </Win96WindowManagerContext.Provider>
  )
}

export const useWin96WindowManager = (): WindowManagerValue => {
  const ctx = useContext(Win96WindowManagerContext)
  if (!ctx) {
    throw new Error('useWin96WindowManager must be used within Win96WindowManagerProvider')
  }

  return ctx
}
