import fs from 'fs/promises'
import path from 'path'

const TICK3 = '\`\`\`'
const TICK1 = '\`'

const contentMap = {
  'src/features/kb/routes/KB/12. Linux & Shell Administration/strace/index.mdx': `---
title: strace (System Call Trace)
description: The ultimate diagnostic tool used to intercept and record the raw system calls a program makes directly to the Linux Kernel.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="strace (System Call Trace)">

When a program wants to read a file, open a network port, or allocate memory, it cannot do it directly. It must ask the Linux Kernel for permission by triggering a **System Call** (syscall).

**TICK1straceTICK1** is a diagnostic tool that attaches to a process and prints every single syscall it makes in real-time.

## The Power of strace

Sysadmins use TICK1straceTICK1 when a program is failing silently, and the application logs are completely empty.

For example, if you launch Nginx and it immediately crashes with no error message, you can run:
TICK1strace nginxTICK1

You will see thousands of lines of output as Nginx boots up. Near the very bottom, right before the crash, you might see:
TICK1openat(AT_FDCWD, "/etc/nginx/nginx.conf", O_RDONLY) = -1 EACCES (Permission denied)TICK1

Without looking at a single log file, TICK1straceTICK1 just proved mathematically that the crash is being caused by a file permission error on the configuration file.

<Callout icon="warning" title="Performance Impact">
  Running TICK1straceTICK1 on a process intercepts every single interaction with the Kernel. This causes massive overhead, often slowing the application down by 50x to 100x. Never run TICK1straceTICK1 on a high-traffic production database, or you will instantly cause a massive latency outage.
</Callout>

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/sudo/index.mdx': `---
title: sudo (Superuser Do)
description: The critical security utility that allows standard users to temporarily execute specific commands with absolute Root privileges.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="sudo (Superuser Do)">

Logging in directly as the TICK1rootTICK1 user is highly dangerous. If you leave your terminal unlocked, anyone can destroy the server. 
Instead, Linux uses **TICK1sudoTICK1** (Superuser Do). 

It allows authorized standard users to prefix their commands with TICK1sudoTICK1 (e.g., TICK1sudo systemctl restart nginxTICK1). The system will prompt the user for *their own password* (not the Root password), execute that single command as Root, and then immediately return to standard privileges.

## The visudo File

How does the system know who is allowed to use TICK1sudoTICK1? 
It checks the **TICK1/etc/sudoersTICK1** file.

<Callout icon="warning" title="The visudo Command">
  You must **never** edit TICK1/etc/sudoersTICK1 directly using Nano or Vim. If you make a syntax typo and save the file, you will instantly break the TICK1sudoTICK1 command globally, permanently locking yourself out of Root access. 
  You must always edit it by running the **TICK1visudoTICK1** command. TICK1visudoTICK1 opens the file in a temporary buffer, and when you save, it mathematically verifies the syntax before actually applying it to the real file.
</Callout>

## Granular Permissions
The true power of the TICK1sudoersTICK1 file is granularity. You don't have to give a user full Root access. 
You can add a line like: TICK1alice ALL=(ALL) /bin/systemctl restart nginxTICK1
This allows Alice to use TICK1sudoTICK1 to restart the web server, but if she tries to TICK1sudo rm -rf /TICK1, the system will explicitly deny her.

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/syslog/index.mdx': `---
title: syslog
description: The legacy, plain-text system logging protocol and daemon that formed the backbone of Linux monitoring for decades.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="syslog">

Before TICK1systemdTICK1 and binary logs took over, the standard for Linux logging was **syslog** (handled by daemons like TICK1syslogdTICK1 or TICK1rsyslogTICK1). 

TICK1syslogTICK1 is both a protocol and a daemon. It listens for log messages generated by the Kernel or user-space applications and routes them to specific plain-text files inside TICK1/var/log/TICK1 based on a set of rules defined in TICK1/etc/syslog.confTICK1.

## Facilities and Severities

Every syslog message is tagged with two pieces of metadata:
1. **Facility**: What type of program generated the log (e.g., TICK1authTICK1 for security, TICK1mailTICK1 for email, TICK1cronTICK1 for scheduled tasks, or TICK1local0-7TICK1 for custom apps).
2. **Severity**: How bad is it? (e.g., 0=Emergency, 3=Error, 6=Info, 7=Debug).

<Callout icon="info" title="Remote Logging">
  The greatest strength of TICK1syslogTICK1 is its built-in network capability. You can configure TICK1rsyslogTICK1 on 50 different web servers to forward all their logs over UDP Port 514 to a single, centralized "Syslog Server". This ensures that if a web server is hacked and deleted, the logs of the hack are safely preserved on a different machine.
</Callout>

## Modern Compatibility
Even though TICK1systemd-journaldTICK1 is the default on modern Linux, TICK1rsyslogTICK1 is usually still installed alongside it. TICK1journaldTICK1 acts as the primary collector, and then quietly forwards a copy of all the logs to TICK1rsyslogTICK1 so that the traditional plain-text files in TICK1/var/log/TICK1 continue to function for legacy monitoring tools.

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/system monitoring/index.mdx': `---
title: System Monitoring
description: An overview of the critical methodologies and philosophies used by administrators to monitor the health of Linux infrastructure.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="System Monitoring">

A sysadmin cannot manually SSH into 500 servers every morning to run TICK1htopTICK1. **System Monitoring** is the practice of automating the collection, aggregation, and alerting of server health metrics.

## The Three Pillars of Observability

Modern infrastructure monitoring is broken down into three distinct categories:

1. **Metrics (The "What")**: Numerical data points collected over time. (e.g., "CPU usage is at 95%"). Tools like **Prometheus** or **Datadog** constantly scrape these numbers and store them in Time-Series Databases.
2. **Logs (The "Why")**: Unstructured text data emitted by applications. (e.g., "Error: Database connection timeout"). Tools like the **ELK Stack (Elasticsearch, Logstash, Kibana)** or **Splunk** ingest millions of logs a minute, allowing admins to search for the root cause of the CPU spike.
3. **Traces (The "Where")**: Following a single user's request as it bounces across 20 different microservices. (e.g., "The request took 5 seconds, and 4.8 of those seconds were spent waiting on the Payment API").

<Callout icon="warning" title="Alert Fatigue">
  The biggest mistake junior admins make is configuring alerts for everything. If a Sysadmin's phone buzzes 50 times a day for minor CPU spikes, they will start ignoring the alerts (Alert Fatigue). When a real catastrophic failure happens, it will be ignored. Alerts should only trigger for actionable, critical failures (e.g., "The main database has crashed", or "The hard drive will be 100% full in 2 hours").
</Callout>

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/systemctl/index.mdx': `---
title: systemctl
description: The primary command-line tool used by administrators to interact with systemd and manage background services.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="systemctl">

If TICK1systemdTICK1 is the brain of the modern Linux operating system, **TICK1systemctlTICK1** is the keyboard you use to talk to it.

It is the primary command used to start, stop, restart, and monitor background services (Daemons).

## Core Commands

- **TICK1sudo systemctl start nginxTICK1**: Starts the Nginx service.
- **TICK1sudo systemctl stop nginxTICK1**: Stops it.
- **TICK1sudo systemctl restart nginxTICK1**: Fully stops and then starts it (drops active connections).
- **TICK1sudo systemctl reload nginxTICK1**: Asks Nginx to reread its configuration file from disk *without* dropping active connections (graceful reload).

<Callout icon="info" title="Enable vs Start">
  Starting a service only runs it for the current session. If the server reboots, the service will stay dead.
  To ensure a service boots automatically when the server turns on, you must use **TICK1sudo systemctl enable nginxTICK1**. This creates a physical symlink in the FHS tree telling the Kernel to launch it on boot.
</Callout>

## Viewing Status
The most important command for debugging is **TICK1systemctl status nginxTICK1**.
It prints a beautifully formatted summary showing:
1. Is it actively running? (Usually highlighted in bright green).
2. Is it Enabled for boot?
3. The exact PID of the main process.
4. The last 10 lines of the service's log output from TICK1journaldTICK1.

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/systemd/index.mdx': `---
title: systemd
description: The massive, monolithic system and service manager that has become the default architecture for almost all modern Linux distributions.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="systemd">

**systemd** is the software suite that fundamentally replaced the ancient SysVinit architecture. It is assigned **PID 1**, meaning it is the very first process launched by the Kernel, and it is responsible for booting the rest of the operating system.

## The Architecture of Units

Unlike legacy init systems that used messy bash scripts, TICK1systemdTICK1 uses declarative, INI-style configuration files called **Units**. 
There are multiple types of Units:
- **TICK1.serviceTICK1**: Defines a background daemon (like Nginx or SSH).
- **TICK1.timerTICK1**: The modern replacement for TICK1cronTICK1. It triggers other units at specific times.
- **TICK1.mountTICK1**: Mounts filesystems (slowly replacing TICK1/etc/fstabTICK1).

<Callout icon="success" title="Advanced Process Tracking (cgroups)">
  In the old SysVinit days, if a web server spawned a child process, and then the parent crashed, the child process would become a "Zombie" floating invisibly in RAM forever. 
  TICK1systemdTICK1 solves this using Kernel **cgroups**. It places every service into an isolated tracking group. If you run TICK1systemctl stop nginxTICK1, TICK1systemdTICK1 guarantees that the parent and every single child process it ever spawned are instantly executed.
</Callout>

## The Monolith
TICK1systemdTICK1 is highly controversial because it has absorbed massive amounts of OS functionality. It now handles system logging (TICK1journaldTICK1), network configuration (TICK1systemd-networkdTICK1), DNS resolution (TICK1systemd-resolvedTICK1), and even user login management (TICK1systemd-logindTICK1). 

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/tar/index.mdx': `---
title: tar (Tape Archive)
description: The ancient but ubiquitous utility used to bundle thousands of files into a single solid block of data, known as a Tarball.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="tar (Tape Archive)">

The **TICK1tarTICK1** command was originally created in 1979 to sequentially write data onto physical magnetic tape drives. 
Today, it is the absolute standard for archiving data in Linux.

Because the standard Linux compressor (TICK1gzipTICK1) can only compress *one single file at a time*, sysadmins use TICK1tarTICK1 to bundle 1,000 files into a single, uncompressed TICK1.tarTICK1 block. They then pass that single block to TICK1gzipTICK1, resulting in a **.tar.gz** file (a Tarball).

## The Famous Command Flags

The TICK1tarTICK1 flags are notoriously difficult to memorize. You almost always use four flags clustered together:

- **Create an Archive (TICK1-czvfTICK1)**: 
  TICK1tar -czvf backup.tar.gz /var/www/html/TICK1
  *(c = Create, z = Compress with Gzip, v = Verbose output, f = The filename of the archive).*

- **Extract an Archive (TICK1-xzvfTICK1)**: 
  TICK1tar -xzvf backup.tar.gzTICK1
  *(x = eXtract).*

<Callout icon="warning" title="The Order of 'f'">
  The TICK1fTICK1 flag must **always** be the absolute last flag in the cluster. The TICK1fTICK1 flag tells the command "the very next word I type is the filename". If you type TICK1tar -cfzv archive.tar.gzTICK1, the command will literally try to create a file named "zv".
</Callout>

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/top/index.mdx': `---
title: top
description: The classic, default, real-time system monitor installed on virtually every Unix and Linux machine in existence.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="top">

Before TICK1htopTICK1 existed, there was **TICK1topTICK1**. 

It is a command-line utility that provides a dynamic, real-time view of a running system. It is installed by default on everything from macOS to Alpine Linux containers. If you SSH into a highly restricted enterprise server where you cannot install custom software, TICK1topTICK1 is your best friend.

## Reading the Output

The top half of the screen shows global system metrics:
- **Uptime**: How long the server has been running.
- **Load Average**: Three numbers representing the system load over the last 1, 5, and 15 minutes. (A load of 1.00 on a single-core CPU means the CPU is at exactly 100% capacity).
- **CPU States**: Breaks down CPU usage by TICK1usTICK1 (User processes), TICK1syTICK1 (System/Kernel), and TICK1idTICK1 (Idle).

The bottom half shows the process list, sorted by default by CPU usage.

<Callout icon="info" title="Interactive Commands">
  While not as pretty as TICK1htopTICK1, TICK1topTICK1 is interactive. 
  While it is running, press **TICK1MTICK1** (Shift+M) to instantly resort the list by Memory usage, or press **TICK1kTICK1** to prompt for a PID to kill.
</Callout>

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/ufw/index.mdx': `---
title: UFW (Uncomplicated Firewall)
description: The default, heavily simplified firewall configuration tool used in Ubuntu to manage underlying iptables/nftables rules.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="UFW (Uncomplicated Firewall)">

Configuring raw TICK1iptablesTICK1 rules is a miserable experience. If you make a typo, you can instantly lock yourself out of your cloud server, forcing you to destroy the instance and start over.

To solve this, Canonical (the makers of Ubuntu) created **UFW (Uncomplicated Firewall)**. 
It is a frontend abstraction. You type simple English commands, and UFW writes the complex TICK1iptablesTICK1 syntax in the background.

## Basic Usage

By default, UFW is usually installed but disabled. 

1. **Set Default Policies**:
   TICK1sudo ufw default deny incomingTICK1
   TICK1sudo ufw default allow outgoingTICK1
2. **Allow SSH (CRITICAL before enabling)**:
   TICK1sudo ufw allow 22/tcpTICK1
3. **Allow Web Traffic**:
   TICK1sudo ufw allow 80/tcpTICK1
   TICK1sudo ufw allow 443/tcpTICK1
4. **Enable the Firewall**:
   TICK1sudo ufw enableTICK1

<Callout icon="warning" title="The SSH Lockout Danger">
  The single most common mistake junior admins make is running TICK1ufw enableTICK1 *before* they explicitly run TICK1ufw allow 22TICK1. Because the default policy denies all incoming traffic, the second they hit Enter, their SSH tunnel is instantly severed, and they can never get back into the server.
</Callout>

## Viewing Status
Running TICK1sudo ufw status numberedTICK1 provides a perfectly clean, readable list of all active firewall rules, with index numbers allowing you to easily delete specific rules (e.g., TICK1sudo ufw delete 3TICK1).

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/umask/index.mdx': `---
title: umask (User File-Creation Mode Mask)
description: The hidden system setting that dictates the default, base permissions granted to any new file or directory upon creation.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="umask (User File-Creation Mode Mask)">

When you create a brand new file using TICK1touch secret.txtTICK1, what permissions does it get? 
Linux doesn't ask you. It calculates the default permissions dynamically using a mechanism called the **umask**.

## The Subtraction Logic

In Linux, the maximum base permission for a Directory is **777** (Read/Write/Execute for everyone). 
The maximum base permission for a File is **666** (Read/Write for everyone; standard files do not get Execute permissions by default).

The **umask** is a 3-digit octal number that is *subtracted* from those maximums.

If your system's umask is configured to **022**:
- **New Directories**: 777 - 022 = **755** (Owner gets full control, everyone else can only Read/Execute).
- **New Files**: 666 - 022 = **644** (Owner gets Read/Write, everyone else can only Read).

<Callout icon="success" title="Enterprise Security (Umask 027)">
  By default, most consumer Linux distributions use a umask of TICK1022TICK1, which means any file you create is globally readable by every other user on the server. 
  In high-security enterprise environments, the default umask is often changed in TICK1/etc/profileTICK1 to **027**. This subtracts 7 from the "Others" column, guaranteeing that new files are permanently locked to the Owner and Group, with zero access for anyone else.
</Callout>

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/wget/index.mdx': `---
title: wget
description: The classic, non-interactive command-line utility used heavily for downloading files and mirroring entire websites.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="wget">

While TICK1curlTICK1 is designed to stream data and interact with complex REST APIs, **TICK1wgetTICK1 (Web Get)** is designed to do exactly one thing: Download files to the hard drive as reliably as possible.

It is a non-interactive downloader. You give it a URL, and it handles the rest in the background, even on wildly unstable networks.

## Core Features

- **Standard Download**: TICK1wget https://example.com/file.zipTICK1 (Downloads the file and saves it in the current directory with its original name).
- **Resume Broken Downloads (TICK1-cTICK1)**: If you are downloading a 50GB ISO and your internet cuts out at 49GB, you simply run TICK1wget -c https://example.com/file.isoTICK1. TICK1wgetTICK1 will look at the partial file on disk and seamlessly resume the download exactly where it left off.
- **Run in Background (TICK1-bTICK1)**: TICK1wget -b https://example.com/massive.zipTICK1. Immediately detaches the process, allowing you to close your terminal while it finishes downloading.

<Callout icon="warning" title="Website Mirroring">
  TICK1wgetTICK1 is incredibly powerful at recursive downloading (TICK1-rTICK1). If you run TICK1wget -m https://example.comTICK1, TICK1wgetTICK1 will download the homepage, parse the HTML, find every single hyperlink, and recursively download every image, CSS file, and subpage until it has a perfect, offline, physical copy of the entire website on your hard drive.
</Callout>

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/xargs/index.mdx': `---
title: xargs
description: The essential shell utility that converts streams of piped text into discrete command-line arguments for other programs.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="xargs">

The Unix Pipe (TICK1|TICK1) is amazing, but it has a massive flaw: Many legacy Unix commands (like TICK1rmTICK1, TICK1cpTICK1, TICK1mkdirTICK1) do not know how to read data from Standard Input.

If you run TICK1find . -name "*.log" | rmTICK1, it will fail. TICK1rmTICK1 completely ignores the pipe and waits for you to type arguments.

**TICK1xargsTICK1** solves this. It acts as a bridge. It reads the piped text, breaks it apart, and dynamically appends it as arguments to the end of the next command.

## Usage

- **TICK1find . -name "*.log" | xargs rmTICK1**: 
  TICK1xargsTICK1 takes the list of 50 log files generated by TICK1findTICK1, and dynamically executes TICK1rm file1.log file2.log file3.log...TICK1

<Callout icon="warning" title="The Spaces in Filenames Problem">
  By default, TICK1xargsTICK1 breaks text apart using spaces. If a file is named TICK1"my report.txt"TICK1, TICK1xargsTICK1 will think that is two separate files and try to delete TICK1myTICK1 and TICK1report.txtTICK1.
  To solve this, you must always use the "Null Terminator" flags. 
  TICK1find . -name "*.log" -print0 | xargs -0 rmTICK1
  This forces TICK1findTICK1 and TICK1xargsTICK1 to use the invisible TICK1\0TICK1 character to separate files, completely immune to spaces in filenames.
</Callout>

## Parallel Execution
A hidden superpower of TICK1xargsTICK1 is the TICK1-PTICK1 flag. 
If you have 100 images you need to compress, TICK1ls *.jpg | xargs -P 4 compressTICK1 will execute the compression command using 4 parallel CPU threads simultaneously, drastically reducing execution time.

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/yum/index.mdx': `---
title: YUM (Yellowdog Updater, Modified)
description: The legendary, albeit legacy, package manager that powered the Red Hat and CentOS ecosystems for over a decade.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="YUM (Yellowdog Updater, Modified)">

Before TICK1dnfTICK1 existed, the Red Hat Enterprise Linux (RHEL) ecosystem was entirely managed by **YUM**. 

YUM was a massive leap forward from manually installing raw TICK1.rpmTICK1 files. Like Debian's APT, YUM could reach out to remote repositories over HTTP, automatically calculate dependency chains, and install an entire software stack in a single command.

## The Legacy of YUM

While TICK1yumTICK1 is officially deprecated and replaced by TICK1dnfTICK1 in RHEL 8+, its legacy is so massive that the command still exists on modern systems. If you type TICK1yum install nginxTICK1 on a brand new Rocky Linux 9 server, it will work perfectly (because the OS secretly symlinks the TICK1yumTICK1 command directly to the TICK1dnfTICK1 binary in the background).

<Callout icon="info" title="The Flaws of YUM">
  YUM was eventually replaced because it was written heavily in Python, consumed massive amounts of RAM (often crashing tiny 512MB cloud servers during updates), and its dependency resolution algorithm was notoriously slow and sometimes mathematically inaccurate. TICK1dnfTICK1 solved all of these issues by rewriting the core logic in C++.
</Callout>

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/zip/index.mdx': `---
title: zip & unzip
description: The universally recognized, cross-platform archive format, primarily used to interface with Windows and macOS systems.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="zip & unzip">

While Linux systems overwhelmingly prefer TICK1.tar.gzTICK1 files, the rest of the computing world (Windows, macOS) uses **ZIP** files. 

Because of this, the TICK1zipTICK1 and TICK1unzipTICK1 utilities are almost always installed on Linux servers to handle files uploaded by standard users.

## How ZIP is Different from Gzip/Tar

1. **All-in-One**: A single TICK1.zipTICK1 file both bundles multiple files together (like TICK1tarTICK1) and compresses them (like TICK1gzipTICK1) simultaneously.
2. **Individual Access**: If a Zip file contains 1,000 images, you can instantly extract exactly one specific image from it. A Tarball is a "Solid Archive", meaning to get the 1,000th image, the computer has to sequentially decompress the entire massive block from the very beginning.

## Basic Usage

- **Compressing a Directory (TICK1-rTICK1 for Recursive)**:
  TICK1zip -r website_backup.zip /var/www/html/TICK1
- **Extracting a ZIP file**:
  TICK1unzip website_backup.zip -d /home/user/extracted/TICK1

<Callout icon="warning" title="Linux Metadata Loss">
  Sysadmins never use ZIP files for internal Linux system backups. The ZIP format was originally designed for MS-DOS. It fundamentally does not understand advanced Linux filesystem metadata. If you ZIP a directory, it strips away File Ownership (UID/GID), advanced ACL permissions, and often breaks Symbolic Links, permanently destroying that metadata.
</Callout>

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/zypper/index.mdx': `---
title: zypper
description: The highly advanced, feature-rich package manager that powers the SUSE and openSUSE enterprise Linux ecosystems.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="zypper">

While Ubuntu uses TICK1aptTICK1 and Red Hat uses TICK1dnfTICK1, the massive German enterprise Linux vendor SUSE (and its community variant openSUSE) relies entirely on **zypper**.

TICK1zypperTICK1 is widely considered one of the most powerful and fastest package managers in the Linux world. It uses the exact same TICK1.rpmTICK1 package format as Red Hat, but utilizes a radically different dependency solver called TICK1libzyppTICK1.

## Syntax

TICK1zypperTICK1 commands are very straightforward, and it supports ultra-short abbreviations:
- **TICK1sudo zypper refreshTICK1 (or TICK1zypper refTICK1)**: Updates the local cache database.
- **TICK1sudo zypper updateTICK1 (or TICK1zypper upTICK1)**: Updates all installed software.
- **TICK1sudo zypper install nginxTICK1 (or TICK1zypper in nginxTICK1)**: Installs Nginx.

<Callout icon="success" title="The Power of Btrfs Snapshots">
  The true magic of TICK1zypperTICK1 is not the command itself, but how openSUSE integrates it with the Btrfs filesystem. 
  Every single time you run a TICK1zypper installTICK1 command, the operating system instantly takes a freeze-frame snapshot of the entire hard drive. If the software update completely destroys the server and causes a Kernel Panic, you simply reboot, select the previous snapshot in the GRUB boot menu, and the server instantly reverts to exactly how it was 30 seconds ago.
</Callout>

</ConceptTemplate>
`,
}

async function main() {
  for (const [filePath, content] of Object.entries(contentMap)) {
    const fullPath = path.resolve(filePath)
    await fs.mkdir(path.dirname(fullPath), { recursive: true })

    // Safely replace TICK1 and TICK3 placeholders with actual backticks
    // This entirely avoids JSON/regex parsing issues.
    let finalContent = content.replace(/TICK3/g, TICK3).replace(/TICK1/g, TICK1)

    // Append a safe newline
    await fs.writeFile(fullPath, finalContent.trim() + '\n', 'utf-8')
    console.log('Wrote ' + filePath)
  }
}

main().catch(console.error)
