import fs from 'fs/promises'
import path from 'path'

const TICK3 = '\`\`\`'
const TICK1 = '\`'

const contentMap = {
  'src/features/kb/routes/KB/12. Linux & Shell Administration/journald/index.mdx': `---
title: systemd-journald
description: The background daemon responsible for collecting and indexing massive amounts of structured binary log data across the OS.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="systemd-journald">

Before TICK1systemdTICK1, Linux logging was handled by TICK1syslogdTICK1 (or TICK1rsyslogTICK1), which simply wrote raw, unstructured text to files like TICK1/var/log/messagesTICK1.

**TICK1systemd-journaldTICK1** fundamentally changed how Linux handles logging. It is a deeply integrated background daemon that captures stdout, stderr, kernel events, and application logs, storing them entirely in a structured **binary** format.

## Why Binary?

Traditional Unix admins hated the shift to binary logs because they could no longer use TICK1catTICK1 to read them. However, TICK1journaldTICK1 provides massive benefits:
1. **Cryptographic Sealing**: Binary logs can be cryptographically sealed. If a hacker breaches a server and tries to delete the log showing their entry, TICK1journaldTICK1 will instantly detect the tampering.
2. **Indexing**: Because the logs are structured, TICK1journaldTICK1 automatically attaches hidden metadata to every single line (e.g., the exact PID, User ID, and Systemd Unit that generated the text).
3. **Storage Efficiency**: Binary logs are compressed automatically and rotate predictably.

<Callout icon="info" title="Interacting with the Journal">
  You cannot read the raw TICK1.journalTICK1 files directly. You must use the **TICK1journalctlTICK1** command to query the database. Many modern systems configure TICK1journaldTICK1 to forward its data to a legacy TICK1syslogTICK1 daemon specifically so older text-parsing tools continue to work.
</Callout>

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/logs/index.mdx': `---
title: Linux Logging
description: The standard locations and conventions for finding system, application, and security logs on a traditional Linux filesystem.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Linux Logging">

Even with the modern dominance of TICK1systemd-journaldTICK1, countless third-party applications (like Nginx, Apache, MySQL) still rely on the traditional Unix philosophy: writing raw text files directly to the hard drive.

By FHS standard, almost all logs in a Linux system live inside the **TICK1/var/log/TICK1** directory.

## Critical Log Files

As a Linux Administrator, you must know these files by heart:

- **TICK1/var/log/syslogTICK1 (or TICK1messagesTICK1)**: The absolute kitchen sink. Almost all general system activity, cron job executions, and minor errors end up here.
- **TICK1/var/log/auth.logTICK1 (or TICK1secureTICK1)**: The security ledger. Every single time someone tries to SSH into the server, use TICK1sudoTICK1, or log in via the console, it is recorded here. This is the first place you look if you suspect a breach.
- **TICK1/var/log/kern.logTICK1**: Messages specifically generated by the Linux Kernel.
- **TICK1/var/log/dmesgTICK1**: A static snapshot of the Kernel ring buffer taken specifically during the boot process.

<Callout icon="warning" title="Log Rotation">
  If Nginx writes every web request to TICK1access.logTICK1, the file will eventually consume the entire hard drive. Linux solves this with a utility called **TICK1logrotateTICK1**. It runs via a daily cron job, renames the current log to TICK1access.log.1.gzTICK1 (compressing it), and creates a fresh, empty TICK1access.logTICK1 file, deleting archives older than a few weeks.
</Callout>

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/kill/index.mdx': `---
title: kill
description: The primary command used to send software Signals to running processes, asking them to shut down or reload.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="kill">

The **TICK1killTICK1** command is poorly named. It does not actually kill processes; it simply sends **Signals** to them. It is entirely up to the process (or the Kernel) to decide how to respond to that Signal.

## The Most Common Signals

When you run TICK1kill <PID>TICK1, you are actually sending a specific numerical signal.

1. **SIGTERM (Signal 15 - Terminate)**: This is the default signal. It is a polite request. It tells a web server, "Please stop accepting new connections, save your database writes, and shut down." The application can completely ignore this if it is frozen.
2. **SIGKILL (Signal 9 - Kill)**: TICK1kill -9 <PID>TICK1. This is the nuclear option. The signal never even reaches the application; it goes directly to the Kernel, and the Kernel instantly deletes the process from memory. Open files are corrupted, and data is lost.
3. **SIGHUP (Signal 1 - Hangup)**: TICK1kill -1 <PID>TICK1. Originally used to tell a program the phone line hung up. Today, daemons (like Nginx) interpret this as "Reload your configuration files from disk without actually dropping active connections."

<Callout icon="success" title="killall and pkill">
  If you have 50 Google Chrome processes running, finding their PIDs and typing TICK1killTICK1 50 times is a nightmare.
  Use **TICK1killall chromeTICK1** to instantly send a SIGTERM to every single process named "chrome", or **TICK1pkill -f "python script.py"TICK1** to kill processes matching a specific text pattern.
</Callout>

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/ps/index.mdx': `---
title: ps (Process Status)
description: The fundamental command used to capture a static, instantaneous snapshot of all running processes on the system.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="ps (Process Status)">

While tools like TICK1htopTICK1 provide a live, continuously updating dashboard of running applications, the **TICK1psTICK1 (Process Status)** command takes a static, one-time snapshot of the Kernel's process table.

Because it simply prints text and exits, TICK1psTICK1 is overwhelmingly used in bash scripts and piped into TICK1grepTICK1 for text processing.

## The Legendary "aux"

The TICK1psTICK1 command has the most chaotic flag syntax in all of Linux, due to decades of wars between the Unix (System V) and BSD development camps. 
Today, almost all administrators use the BSD syntax format: **TICK1ps auxTICK1**

- **a**: Show processes for ALL users (not just the current user).
- **u**: Display the output in a user-oriented format (shows the username, CPU%, and Memory%).
- **x**: Show processes that are NOT attached to a terminal (e.g., background daemons like Nginx).

<Callout icon="info" title="The Process Hierarchy">
  If you want to see exactly who spawned who, you can use TICK1ps -ef --forestTICK1. This generates a beautiful ASCII tree, visually linking child processes directly to their parent's PID.
</Callout>

## Common Columns
When you run TICK1ps auxTICK1, you will see several columns:
- **USER / PID**: Who owns it, and its exact Process ID.
- **VSZ / RSS**: Virtual Memory Size (everything the app has requested) vs Resident Set Size (the actual physical RAM it is actively consuming).
- **STAT**: The current state (e.g., TICK1STICK1 for Sleeping, TICK1RTICK1 for Running, TICK1ZTICK1 for Zombie).

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/lsof/index.mdx': `---
title: lsof (List Open Files)
description: The ultimate system administration diagnostic tool used to determine exactly which process is interacting with a specific file or network port.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="lsof (List Open Files)">

In Linux, "Everything is a File". Hard drives are files (TICK1/dev/sdaTICK1), network sockets are files, and directories are files. 

Because of this philosophy, the **TICK1lsofTICK1 (List Open Files)** command is arguably the most powerful diagnostic tool in a sysadmin's arsenal. It asks the Kernel: "Show me every single file that is currently being held open by a process."

## Common Use Cases

### 1. "Device is Busy" Errors
You try to unmount a USB drive using TICK1umount /mnt/usbTICK1, but Linux yells: *"umount: target is busy"*. 
You run: TICK1lsof /mnt/usbTICK1
The output instantly tells you that Alice's TICK1bashTICK1 process (PID 4501) is currently CD'd into that directory, preventing the unmount.

### 2. Identifying Network Ports
If you try to start a Node.js server on Port 8080, but get an *"Address already in use"* error, you can use TICK1lsofTICK1 to find the culprit:
TICK1lsof -i :8080TICK1
It will immediately tell you the exact PID and name of the rogue Java process secretly listening on that network socket.

<Callout icon="warning" title="Running as Root">
  By default, TICK1lsofTICK1 will only show you the files opened by your specific user account. To see files opened by system daemons or other users, you MUST run it using TICK1sudoTICK1, otherwise it will silently hide the data.
</Callout>

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/ltrace/index.mdx': `---
title: ltrace (Library Trace)
description: An advanced debugging tool that intercepts and logs the dynamic library calls a program makes to the operating system.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="ltrace (Library Trace)">

When a compiled C program runs, it rarely executes entirely on its own code. It constantly relies on shared System Libraries (like TICK1glibcTICK1) to perform basic tasks like copying memory strings or calculating math.

**TICK1ltraceTICK1** is a deep diagnostic tool that attaches to a running process and prints exactly which library functions the program is calling in real-time.

## strace vs ltrace

It is critical to understand the difference between TICK1straceTICK1 and TICK1ltraceTICK1:
- **TICK1straceTICK1** traces System Calls (the program talking directly to the Linux Kernel, like "open file" or "send network packet").
- **TICK1ltraceTICK1** traces Library Calls (the program talking to user-space C libraries, like TICK1strlen()TICK1 or TICK1malloc()TICK1).

<Callout icon="success" title="Reverse Engineering and Hacking">
  TICK1ltraceTICK1 is heavily used in cybersecurity Capture The Flag (CTF) events. If you are given a compiled, undocumented binary that asks for a secret password, you can run TICK1ltrace ./binaryTICK1. When you type a fake password, TICK1ltraceTICK1 will intercept the TICK1strcmp(input, "SUPER_SECRET_123")TICK1 library call, instantly revealing the hardcoded password in plain text on your screen.
</Callout>

## Basic Usage
TICK1ltrace ./my_programTICK1 will launch the program and flood your terminal with every C library function it executes, providing a massive window into how the black-box binary was programmed.

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/nice-renice/index.mdx': `---
title: nice & renice
description: The commands used to alter the CPU scheduling priority of a process, making it "nicer" to other applications.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="nice & renice">

In Linux, the Kernel's CPU Scheduler uses a complex algorithm to decide which process gets access to the CPU in any given millisecond. 

You can influence this scheduler using the **TICK1niceTICK1** value. It is literally a measure of how "nice" a process is to the rest of the system. 
- A **highly nice** process will step aside and let other programs use the CPU first. 
- A **very mean** (negative nice) process will aggressively hog the CPU, ignoring everyone else.

## The Nice Scale

Nice values range from **-20 (Highest Priority, Most Aggressive)** to **+19 (Lowest Priority, Nicest)**.
By default, every standard program you launch starts with a nice value of **0**.

- TICK1nice -n 15 tar -czf backup.tar.gz /varTICK1
  This launches a massive, CPU-heavy backup script, but tells it to be very nice (+15). If the web server suddenly gets a spike in traffic, the backup will pause and give the web server the CPU.

<Callout icon="warning" title="Negative Nice Values">
  Any standard user can make their programs "nicer" (0 to 19). However, only the TICK1rootTICK1 user (via TICK1sudoTICK1) is legally allowed to assign a negative nice value (-1 to -20) to prevent standard users from maliciously hoarding the CPU.
</Callout>

## renice
While TICK1niceTICK1 sets the priority of a process *before* it launches, **TICK1reniceTICK1** allows you to alter the priority of a process that is *already running*.
TICK1sudo renice -n -10 -p 4591TICK1 (Makes PID 4591 highly aggressive).

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/mounts/index.mdx': `---
title: mounts
description: The fundamental mechanism of attaching hardware filesystems (hard drives, USBs) to the Linux directory tree.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="mounts">

In Windows, if you plug in a USB drive, it automatically appears as the TICK1E:\TICK1 drive.
In Linux, the Filesystem Hierarchy Standard dictates there is only one single unified tree, starting at TICK1/TICK1.

To access data on a hard drive, you must use the **TICK1mountTICK1** command to graft the drive's filesystem onto an empty folder inside that tree (usually inside TICK1/mntTICK1 or TICK1/mediaTICK1).

## The Mount Command

If you plug in a new SSD, the Kernel will assign it a block device file (e.g., TICK1/dev/sdb1TICK1). 
To make it usable, you create a directory and mount it:

TICK3bash
sudo mkdir /mnt/database
sudo mount /dev/sdb1 /mnt/database
TICK3

Now, any file you write into TICK1/mnt/databaseTICK1 is physically written to the new SSD.

<Callout icon="success" title="Virtual Filesystems">
  TICK1mountTICK1 is not just for physical hardware. Linux heavily relies on virtual, RAM-only filesystems. 
  For example, TICK1/procTICK1 and TICK1/sysTICK1 are actually fake filesystems dynamically generated by the Kernel in RAM. The TICK1mountTICK1 command is used to attach these data structures to the FHS tree so humans can read them using standard text tools like TICK1catTICK1.
</Callout>

## Unmounting (umount)
Before you unplug a USB drive, you must run **TICK1umount /mnt/usbTICK1**. This forces the Kernel to flush all pending, cached data from RAM physically onto the flash memory of the drive. If you unplug it without unmounting, data corruption is almost guaranteed.

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/rsync/index.mdx': `---
title: rsync
description: The legendary, ultra-efficient file synchronization tool used for massive backups and remote server deployments.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="rsync">

If you need to copy a 50GB database file to a remote server, you can use TICK1scpTICK1. However, if the connection drops at 49GB, you have to start the entire transfer over from zero.

**TICK1rsyncTICK1** (Remote Sync) is the industry standard tool for copying and backing up data. It uses a brilliant Delta-Transfer algorithm.

## The Delta Algorithm

If you use TICK1rsyncTICK1 to copy a 50GB file, and then you change a single 10-line text string inside that file, running TICK1rsyncTICK1 again will **not** transfer 50GB. 
It mathematically compares the local file to the remote file, calculates exactly which byte blocks changed, and transfers *only those tiny changes* over the network, taking 3 seconds instead of 3 hours.

## Basic Syntax

TICK1rsyncTICK1 usually operates over a standard encrypted SSH tunnel. 

TICK3bash
# Sync local website files to a remote server
rsync -avz --delete ./public_html/ root@192.168.1.50:/var/www/html/
TICK3

- **-a (Archive)**: Preserves all symlinks, file permissions, and ownership metadata.
- **-v (Verbose)**: Prints what it is doing.
- **-z (Compress)**: Compresses the data on the fly during network transit.
- **--delete**: This is the "Mirror" flag. If you delete an image from your local laptop, this flag tells TICK1rsyncTICK1 to explicitly delete that same image on the remote server to ensure they are perfectly identical.

<Callout icon="warning" title="The Trailing Slash">
  In TICK1rsyncTICK1, the trailing slash is incredibly important. 
  TICK1rsync -a ./folder /destTICK1 will copy the entire folder itself into the destination.
  TICK1rsync -a ./folder/ /destTICK1 (WITH the slash) means "copy the *contents* of this folder" into the destination.
</Callout>

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/networking basics/index.mdx': `---
title: Networking Basics (ip & ss)
description: The modern iproute2 suite of tools used to configure IP addresses, view routing tables, and analyze open sockets.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Networking Basics (ip & ss)">

For decades, Linux administrators used tools like TICK1ifconfigTICK1 (to view IP addresses) and TICK1netstatTICK1 (to view open ports). 
These tools are technically obsolete and missing from many modern distributions. They have been replaced by the **iproute2** suite, primarily the TICK1ipTICK1 and TICK1ssTICK1 commands.

## The 'ip' Command

The TICK1ipTICK1 command is incredibly powerful, managing everything from basic addressing to complex BGP routing tables.

- **View your IP Addresses**: TICK1ip addr showTICK1 (or simply TICK1ip aTICK1).
- **View your Routing Table**: TICK1ip routeTICK1 (Shows you exactly where traffic goes, including your Default Gateway router).
- **Bring an interface online**: TICK1sudo ip link set eth0 upTICK1.

<Callout icon="info" title="Ephemeral Configuration">
  It is critical to remember that if you assign an IP address using the TICK1ipTICK1 command (e.g., TICK1ip addr add 192.168.1.50/24 dev eth0TICK1), that configuration lives entirely in RAM. The second the server reboots, the IP address vanishes. Permanent IP configuration must be handled by daemons like NetworkManager or systemd-networkd.
</Callout>

## The 'ss' Command (Socket Statistics)
TICK1ssTICK1 is the modern replacement for TICK1netstatTICK1. Sysadmins use it constantly to determine what ports are open on a server.
- **TICK1ss -tulpnTICK1**: The golden command. 
  - **t/u**: Show TCP and UDP sockets.
  - **l**: Show only Listening (open server) sockets.
  - **p**: Show the exact Process Name (Nginx/SSH) attached to that socket.
  - **n**: Show raw numeric IP addresses, bypassing slow DNS resolution.

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/nftables/index.mdx': `---
title: nftables
description: The modern, high-performance Linux Kernel firewall subsystem designed to completely replace the legacy iptables architecture.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="nftables">

For 20 years, TICK1iptablesTICK1 was the absolute king of Linux firewalls. However, its architecture was deeply flawed. Every time a Sysadmin added a single new firewall rule, the Kernel had to flush the entire massive ruleset from memory and reload it, causing massive latency spikes on huge enterprise routers.

To fix this, the Linux Kernel developers created **nftables**.

## The Architecture

TICK1nftablesTICK1 operates via a unified user-space tool called **TICK1nftTICK1**. 
Unlike TICK1iptablesTICK1 (which hardcoded Tables and Chains into the Kernel), TICK1nftablesTICK1 provides a completely blank slate. You define your own custom tables, meaning the firewall uses virtually zero CPU if it's not configured.

TICK1nftablesTICK1 also compiles its rules into a specialized, ultra-fast bytecode (similar to eBPF) before pushing them into the Kernel.

## Modern Syntax
The TICK1nftTICK1 syntax was heavily inspired by the TICK1tcpdumpTICK1 network analyzer, making it much easier to read than ancient TICK1iptablesTICK1 flags.

TICK3bash
# Create a blank table
nft add table inet my_firewall

# Add a base chain to intercept incoming traffic, dropping by default
nft add chain inet my_firewall inbound { type filter hook input priority 0 \; policy drop \; }

# Allow SSH port 22
nft add rule inet my_firewall inbound tcp dport 22 accept
TICK3

<Callout icon="success" title="The iptables-nft Wrapper">
  Because replacing thousands of legacy Bash scripts overnight is impossible, modern Linux distributions ship with a tool called TICK1iptables-nftTICK1. When an old script runs an TICK1iptablesTICK1 command, this wrapper silently intercepts the command, translates it into TICK1nftablesTICK1 bytecode, and pushes it to the new engine.
</Callout>

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/package managers (apt/index.mdx': `---
title: apt (Advanced Package Tool)
description: The massively popular package manager powering Debian, Ubuntu, and the vast majority of consumer Linux distributions.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="apt (Advanced Package Tool)">

If you have ever used Ubuntu, Linux Mint, or a Raspberry Pi, you have used **APT (Advanced Package Tool)**. 
Built by the Debian project, APT changed the Linux world by being one of the first systems to automatically download and install software dependencies over the internet.

Under the hood, Debian software is distributed as TICK1.debTICK1 files. The low-level TICK1dpkgTICK1 tool actually installs the files, while TICK1aptTICK1 handles the high-level logic of contacting remote servers and calculating dependencies.

## The Two-Step Update Process

Unlike Windows, TICK1aptTICK1 does not constantly poll servers in the background. It relies on a local database (cache) of available software stored on your hard drive. 

Therefore, installing software is always a two-step process:
1. **TICK1sudo apt updateTICK1**: Reaches out to the Ubuntu servers, downloads the newest list of available software, and updates the local cache. (This does NOT install anything).
2. **TICK1sudo apt upgradeTICK1**: Compares your installed software against the newly downloaded list, and physically downloads/installs the newer versions.

<Callout icon="info" title="apt vs apt-get">
  For decades, the command was TICK1apt-getTICK1. In 2014, Debian released the TICK1aptTICK1 command, which is a wrapper that combines TICK1apt-getTICK1 and TICK1apt-cacheTICK1 into a single, user-friendly tool that features a colorful progress bar. While TICK1aptTICK1 is perfect for humans, it explicitly warns you not to use it in automated Bash scripts, where the older, stable TICK1apt-getTICK1 is still required.
</Callout>

## PPA Repositories
Because Debian values extreme stability, software in the official TICK1aptTICK1 repositories is often years out of date. Ubuntu solved this by introducing **PPAs (Personal Package Archives)**, allowing developers to host their own third-party TICK1aptTICK1 repositories, enabling users to easily install cutting-edge software.

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/pacman/index.mdx': `---
title: pacman
description: The violently fast, simplistic package manager powering the Arch Linux ecosystem and the Steam Deck.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="pacman">

**pacman** is the official package manager for Arch Linux. Unlike Debian's APT or Red Hat's DNF, which are highly complex Python or C++ applications designed for enterprise stability, TICK1pacmanTICK1 is written purely in C with one goal: **Speed**.

It is famously used on Valve's SteamOS (Steam Deck).

## The Rolling Release Model

TICK1pacmanTICK1 does not handle "Major Version Upgrades" (like upgrading from Ubuntu 20.04 to 22.04). 
Arch Linux is a **Rolling Release** distribution. You install it once, and TICK1pacmanTICK1 continuously upgrades individual pieces of the OS every single day, keeping you on the absolute bleeding edge of software development.

## The Flag Syntax

The TICK1pacmanTICK1 syntax is entirely unique. It uses single-letter flags (mostly based around the TICK1-STICK1 flag for "Sync") instead of English verbs.

- **TICK1sudo pacman -SyuTICK1**: The most famous command in Arch Linux. It Syncs the repository databases (TICK1yTICK1) and Upgrades all packages (TICK1uTICK1).
- **TICK1sudo pacman -S firefoxTICK1**: Syncs (Installs) Firefox from the repository.
- **TICK1sudo pacman -Rns firefoxTICK1**: Removes Firefox, its configuration files, and any orphaned dependencies that are no longer needed.

<Callout icon="warning" title="The AUR (Arch User Repository)">
  The true power of Arch Linux lies in the **AUR**. It is a massive, community-driven database containing build scripts for almost every piece of Linux software ever written. While TICK1pacmanTICK1 itself cannot download from the AUR, users install third-party "AUR Helpers" (like TICK1yayTICK1 or TICK1paruTICK1) that perfectly mimic the TICK1pacmanTICK1 syntax while compiling software directly from source code.
</Callout>

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/pipes/index.mdx': `---
title: Pipes (|)
description: The quintessential Unix mechanism allowing the output of one program to instantly become the input of another.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Pipes (|)">

The core philosophy of Unix, pioneered in 1973, is: *"Write programs that do one thing and do it well. Write programs to work together."*

The mechanism that allows these programs to work together is the **Pipe (TICK1|TICK1)**. It is a vertical bar (usually located above the Enter key).

## Chaining Data Streams

When you use a Pipe, the Shell intercepts the **Standard Output (stdout)** of the command on the left, and physically injects it into the **Standard Input (stdin)** of the command on the right, entirely in RAM, without ever writing to the hard drive.

- **TICK1cat access.log | grep "404"TICK1**: The TICK1catTICK1 command spits out 10,000 lines of text. The Pipe catches it and forces it into TICK1grepTICK1, which filters it down to only the 404 errors.

<Callout icon="success" title="Infinite Chaining">
  You can chain as many pipes together as you want, building massive, complex data processing pipelines directly in the terminal:
  
  TICK1cat access.log | grep "404" | awk '{print $1}' | sort | uniq -c | sort -nr | head -n 5TICK1
  
  This single command reads a log, finds all errors, extracts the IP addresses, counts them, sorts them by the worst offenders, and displays the top 5 hackers.
</Callout>

## The xargs Command
Some older programs (like TICK1rmTICK1) do not know how to read data from Standard Input (a Pipe). 
To fix this, you use the **TICK1xargsTICK1** utility. TICK1xargsTICK1 catches the piped data and dynamically converts it into command-line arguments.
For example: TICK1find . -name "*.tmp" | xargs rmTICK1

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/redirection/index.mdx': `---
title: Redirection (>, <)
description: The fundamental shell operator used to capture output text and permanently write it to files.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Redirection (>, <)">

While Pipes (TICK1|TICK1) send data to other *programs*, **Redirection (TICK1>TICK1)** sends data directly to *files* on the hard drive.

## The Three Data Streams

Every Linux program has three invisible data streams:
1. **Standard Input (stdin / File Descriptor 0)**: Where it reads data from (usually the keyboard).
2. **Standard Output (stdout / File Descriptor 1)**: Where it prints normal text (the screen).
3. **Standard Error (stderr / File Descriptor 2)**: Where it prints error messages (the screen).

## Output Redirection (TICK1>TICK1 and TICK1>>TICK1)

- **Single Bracket (TICK1>TICK1)**: Captures Standard Output, creates a file, and **overwrites** everything in it.
  TICK1echo "Hello World" > output.txtTICK1
- **Double Bracket (TICK1>>TICK1)**: Captures Standard Output and safely **appends** it to the bottom of the file (perfect for logs).
  TICK1echo "Error 500" >> server.logTICK1

<Callout icon="warning" title="Redirecting Errors (2>)">
  By default, TICK1>TICK1 only captures File Descriptor 1 (Normal output). If a command fails, the error message bypasses the redirect and prints to your screen. 
  To capture errors into a file, you must explicitly tell the shell to redirect File Descriptor 2:
  TICK1find / -name "secret" 2> errors.logTICK1
  *(To redirect BOTH normal output and errors to the same place, use the magic syntax TICK1&>TICK1 or TICK12>&1TICK1).*
</Callout>

## The Black Hole (/dev/null)
If you are running a script and you want to completely silence all of its output (ignoring both normal text and errors), you redirect it to the Kernel's legendary black hole:
TICK1./noisy_script.sh &> /dev/nullTICK1

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/12. Linux & Shell Administration/sed/index.mdx': `---
title: sed (Stream Editor)
description: The notoriously cryptic but insanely powerful Unix utility used for on-the-fly text substitution and manipulation.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="sed (Stream Editor)">

If you want to open a file, find a word, and replace it, you usually use a GUI text editor like VS Code or a terminal editor like Nano. 

But what if you need to perform a Find & Replace inside an automated bash script? You use **TICK1sedTICK1 (Stream Editor)**. 
TICK1sedTICK1 reads a stream of text (from a pipe or a file), manipulates it entirely in memory based on a set of rules, and spits the modified text out to the screen.

## The Substitution Command

99% of TICK1sedTICK1 usage revolves around the **Substitution (s)** command.
The syntax uses slashes as delimiters: TICK1sed 's/SEARCH_TERM/REPLACE_TERM/g'TICK1

TICK3bash
# Replace the first instance of 'apple' with 'orange' on every line
echo "I like apples" | sed 's/apple/orange/'

# The 'g' (Global) flag replaces EVERY instance on the line, not just the first
cat config.txt | sed 's/localhost/127.0.0.1/g'
TICK3

<Callout icon="warning" title="In-Place Editing (-i)">
  By default, TICK1sedTICK1 does not modify the original file; it just prints the altered text to the terminal.
  If you want to permanently modify the file on the hard drive, you use the dangerous **TICK1-iTICK1 (In-Place)** flag.
  TICK1sed -i 's/Port 22/Port 2222/' /etc/ssh/sshd_configTICK1
</Callout>

## Advanced Deletions
Because TICK1sedTICK1 supports Regex, you can use it to strip unwanted lines from files.
For example, to print a configuration file but automatically delete every single line that starts with a comment (TICK1#TICK1) or is completely blank:
TICK1sed -e '/^#/d' -e '/^$/d' /etc/nginx/nginx.confTICK1

</ConceptTemplate>
`,
}

async function main() {
  for (const [filePath, content] of Object.entries(contentMap)) {
    const fullPath = path.resolve(filePath)
    await fs.mkdir(path.dirname(fullPath), { recursive: true })

    // Safely replace TICK1 and TICK3 placeholders with actual backticks
    // This entirely avoids JSON/regex parsing issues.
    let finalContent = content.replace(/TICK3/g, TICK3).replace(/TICK1/g, TICK1)

    // Append a safe newline
    await fs.writeFile(fullPath, finalContent.trim() + '\n', 'utf-8')
    console.log('Wrote ' + filePath)
  }
}

main().catch(console.error)
