import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const PROJECT_ROOT = path.resolve(__dirname, '..')
const ROUTE_DIR = path.join(PROJECT_ROOT, 'src', 'features', 'kb', 'routes', 'KB')

const contentMap = {
  '28. Large Language Models/Encoder-only models/index.mdx': `---
title: Encoder-Only Models
description: Transformer architectures designed to understand text context bidirectionally, famously popularized by BERT.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Encoder-Only Models">

Encoder-only models use just the encoder stack of the original Transformer architecture. They are designed to build a deep, bidirectional mathematical understanding of an entire input sequence simultaneously. They are terrible at generating text, but incredible at understanding it.

<Callout icon="success" title="The BERT Revolution">
  In 2018, Google released **BERT** (Bidirectional Encoder Representations from Transformers). It achieved state-of-the-art results on 11 different NLP tasks simultaneously and revolutionized how Google Search understood complex human queries.
</Callout>

## Core Characteristics

<ComparisonTable 
  headers={['Characteristic', 'Description']}
  rows={[
    ['Attention Mechanism', 'Unmasked Self-Attention. Every token in the sequence is allowed to mathematically "look at" every other token, both before and after it.'],
    ['Pretraining Objective', 'Masked Language Modeling (MLM). 15% of the words are hidden (e.g., "The cat sat on the [MASK]"). The model must predict the hidden word based on the surrounding context.'],
    ['Primary Use Cases', 'Sentiment analysis, text classification, named entity recognition (NER), and semantic search embeddings.']
  ]}
/>

</ConceptTemplate>
`,
  '28. Large Language Models/Decoder-only models/index.mdx': `---
title: Decoder-Only Models
description: Autoregressive transformer architectures designed for generative AI, popularized by the GPT family.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Decoder-Only Models">

Decoder-only models use just the decoder stack of the Transformer architecture. They are autoregressive, meaning they predict the very next token in a sequence based only on the preceding tokens. This is the architecture that powers the modern Generative AI revolution.

<Callout icon="info" title="The GPT Paradigm">
  OpenAI bet heavily on the Decoder-only architecture with the Generative Pre-trained Transformer (GPT) series. They discovered that if you make a decoder-only model massive enough and feed it enough text, it develops emergent abilities like reasoning, coding, and translation without specific fine-tuning.
</Callout>

## Core Characteristics

<ComparisonTable 
  headers={['Characteristic', 'Description']}
  rows={[
    ['Attention Mechanism', 'Masked Self-Attention. A token is mathematically blocked from "looking at" any token that comes after it, ensuring it only uses past context to predict the future.'],
    ['Pretraining Objective', 'Next-Token Prediction (Causal Language Modeling). Given a sequence "The cat sat on the", predict the highest probability for the next word (e.g., "mat").'],
    ['Primary Use Cases', 'Chatbots, code generation, creative writing, and any generative AI application.']
  ]}
/>

</ConceptTemplate>
`,
  '28. Large Language Models/Encoder-decoder models/index.mdx': `---
title: Encoder-Decoder Models
description: The original Transformer architecture designed for sequence-to-sequence tasks.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Encoder-Decoder Models">

The Encoder-Decoder model is the exact architecture proposed in the original 2017 "Attention Is All You Need" paper. It combines an Encoder stack to understand the input and a Decoder stack to generate the output.

<Callout icon="tip" title="T5 (Text-to-Text Transfer Transformer)">
  Google\\'s T5 model is the most famous modern example. It frames every single NLP task (translation, summarization, classification) as a text-to-text problem. You feed the encoder "translate English to German: That is good" and the decoder generates "Das ist gut".
</Callout>

## How it Works

1. **The Encoder:** Reads the entire input sequence using unmasked bidirectional attention and compresses it into a dense mathematical representation.
2. **Cross-Attention:** The Decoder generates the output one token at a time. During generation, it uses a special "Cross-Attention" layer to continuously look back at the dense representation generated by the Encoder.
3. **The Output:** The Decoder outputs the final sequence autoregressively.

</ConceptTemplate>
`,
  '28. Large Language Models/Pretraining objectives/index.mdx': `---
title: Pretraining Objectives
description: The self-supervised mathematical tasks used to train massive foundation models on raw internet text.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Pretraining Objectives">

Pretraining is the first, most expensive, and most compute-heavy phase of creating an LLM. Because human-labeled data is too expensive, models are trained using **Self-Supervised Learning** on trillions of words scraped from the internet. The Pretraining Objective defines the exact mathematical game the model plays to learn language.

<Callout icon="warning" title="Compute Cost">
  Pretraining a state-of-the-art model like Llama 3 or GPT-4 requires tens of thousands of GPUs running for months, costing tens of millions of dollars in compute and electricity.
</Callout>

## Standard Objectives

<ComparisonTable 
  headers={['Objective', 'Model Type', 'Mechanism']}
  rows={[
    ['Causal Language Modeling (CLM)', 'Decoder-Only (GPT, Llama)', 'Given previous tokens, predict the exact next token. The model is penalized via Cross-Entropy Loss if it predicts wrong.'],
    ['Masked Language Modeling (MLM)', 'Encoder-Only (BERT)', 'Randomly hide 15% of the tokens in a sequence. The model must predict the hidden tokens using bidirectional context.'],
    ['Span Corruption', 'Encoder-Decoder (T5)', 'Randomly replace sequences of multiple tokens with a single sentinel token. The model must generate the missing sequences.']
  ]}
/>

</ConceptTemplate>
`,
  '28. Large Language Models/Instruction tuning/index.mdx': `---
title: Instruction Tuning
description: The fine-tuning process that turns a raw autocomplete engine into a helpful AI assistant.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Instruction Tuning">

A raw, pre-trained base model (like the original GPT-3) is merely a mathematical autocomplete engine. If you prompt it with "Write a poem about the moon", it might respond with "Write a poem about the sun", because it is just continuing the pattern of a list of writing prompts.

**Instruction Tuning** (Supervised Fine-Tuning or SFT) is the process of training the model on a high-quality dataset of (Prompt, Response) pairs so it learns to follow instructions and act like a chatbot.

<Callout icon="success" title="The ChatGPT Magic">
  ChatGPT was not a new base model; it was GPT-3.5 that had undergone rigorous Instruction Tuning and Reinforcement Learning from Human Feedback (RLHF). This alignment process is what caused the explosive global adoption of AI.
</Callout>

## The Process

1. **Dataset Creation:** Humans write thousands of high-quality examples of prompts and the exact desired answers.
2. **Formatting:** The data is formatted using special chat templates (e.g., adding \`<|user|>\` and \`<|assistant|>\` tokens).
3. **Training:** The model is fine-tuned using standard Backpropagation to mathematically maximize the probability of the assistant\\'s response given the user\\'s prompt.

</ConceptTemplate>
`,
  '28. Large Language Models/Mixture-of-experts (MoE)/index.mdx': `---
title: Mixture-of-Experts (MoE)
description: A neural network architecture that massively scales parameter count while keeping inference compute costs low.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Mixture-of-Experts (MoE)">

Mixture-of-Experts (MoE) is an architectural pattern that replaces standard dense feedforward layers with multiple smaller "Expert" networks and a "Router" network. 

During inference, instead of activating every single parameter in the model, the Router mathematically selects only the top 1 or 2 Experts to process a specific token. This allows you to build a 1-Trillion parameter model that runs as fast as a 100-Billion parameter model.

<Callout icon="info" title="The Open Source MoE Boom">
  Mistral\\'s **Mixtral 8x7B** proved that open-source MoE models could rival GPT-3.5 while running on consumer hardware. It has 47 billion total parameters, but only uses 12 billion parameters during inference.
</Callout>

## Core Components

<ComparisonTable 
  headers={['Component', 'Function']}
  rows={[
    ['The Router (Gating Network)', 'A small neural network that looks at the current token and outputs a probability distribution over the available Experts.'],
    ['The Experts', 'Standard feedforward neural networks. In an 8x MoE, there are 8 independent experts. They often naturally specialize (e.g., one expert becomes good at math, another at French) without explicit human direction.'],
    ['Sparse Activation', 'The defining feature of MoE. The system only executes the math for the top-K experts (usually K=2) chosen by the Router.']
  ]}
/>

</ConceptTemplate>
`,
  '28. Large Language Models/KV cache/index.mdx': `---
title: KV Cache (Key-Value Cache)
description: The critical optimization that makes autoregressive generation in Transformers computationally feasible.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="KV Cache (Key-Value Cache)">

In an autoregressive decoder model, generating the 100th token requires calculating attention scores against the previous 99 tokens. Generating the 101th token requires calculating against the previous 100 tokens. 

Without optimization, the model would re-calculate the mathematical Key (K) and Value (V) matrices for all preceding tokens at every single step, leading to catastrophic $O(N^2)$ computational waste.

<Callout icon="success" title="The Solution">
  The **KV Cache** solves this by saving the computed K and V matrices for past tokens in GPU memory. When generating the next token, the model only computes the K and V for the *new* token, and appends it to the cache.
</Callout>

## The Memory Bottleneck

While KV Caching drastically reduces compute (FLOPs), it consumes a massive amount of VRAM.

<ComparisonTable 
  headers={['Problem', 'Modern Solutions']}
  rows={[
    ['Memory Exhaustion', 'As context windows grow to 1 Million+ tokens, the KV Cache can consume hundreds of gigabytes of VRAM, far exceeding the model weights themselves.'],
    ['Multi-Query Attention (MQA)', 'Forces all attention heads to share a single K and V matrix, drastically reducing KV Cache size with minimal performance loss.'],
    ['Grouped-Query Attention (GQA)', 'A middle ground used by Llama 3: groups of attention heads share a K and V matrix, balancing quality and memory efficiency.']
  ]}
/>

</ConceptTemplate>
`,
  '28. Large Language Models/PEFT/index.mdx': `---
title: Parameter-Efficient Fine-Tuning (PEFT)
description: Techniques to fine-tune massive LLMs on consumer hardware by training only a tiny fraction of parameters.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Parameter-Efficient Fine-Tuning (PEFT)">

Fine-tuning a 70-Billion parameter model requires updating 70 billion weights. The optimizer states and gradients required for this process demand hundreds of gigabytes of VRAM, which is impossible on consumer GPUs.

Parameter-Efficient Fine-Tuning (PEFT) solves this by freezing the massive pretrained base model and mathematically injecting a tiny number of trainable parameters.

<Callout icon="tip" title="LoRA (Low-Rank Adaptation)">
  LoRA is the undisputed king of PEFT. It freezes the base model and injects trainable rank-decomposition matrices into the Transformer layers. It can reduce the number of trainable parameters by 10,000x and GPU memory requirements by 3x, allowing a 7B model to be fine-tuned on a single 16GB gaming GPU.
</Callout>

## Popular PEFT Methods

<ComparisonTable 
  headers={['Method', 'Mechanism']}
  rows={[
    ['LoRA', 'Uses low-rank matrix decomposition to approximate the weight updates. The resulting LoRA "adapter" is often just a few megabytes in size and can be hot-swapped at runtime.'],
    ['QLoRA', 'Quantizes the frozen base model to 4-bit precision, and trains the LoRA adapters in 16-bit precision. This maximizes VRAM efficiency.'],
    ['Prompt Tuning', 'Appends a sequence of trainable continuous "virtual tokens" to the prompt. Only these virtual tokens are updated during backpropagation.']
  ]}
/>

</ConceptTemplate>
`,
  '28. Large Language Models/Tool use/index.mdx': `---
title: Tool Use (Function Calling)
description: Empowering LLMs to interact with the external world by triggering APIs and executing code.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Tool Use (Function Calling)">

By default, an LLM is a frozen mathematical brain trapped in a box. It cannot browse the internet, execute math reliably, or book a flight. 

**Tool Use** (or Function Calling) is the paradigm where the LLM is fine-tuned to recognize when it needs external information, and instead of generating text, it generates a structured JSON object requesting to run a specific tool.

<Callout icon="success" title="The Agentic Workflow">
  This is the foundation of AI Agents. The model outputs a tool call (e.g., \`{"name": "get_weather", "args": {"location": "London"}}\`). The backend intercepts this, executes the actual code, and feeds the result back into the LLM\\'s context window so it can formulate a final answer.
</Callout>

## How Models Learn Tools

Models do not inherently know how to output perfect JSON. They must be explicitly fine-tuned.

<ComparisonTable 
  headers={['Phase', 'Description']}
  rows={[
    ['System Prompting', 'The user injects a JSON Schema describing all available tools into the system prompt.'],
    ['Fine-Tuning', 'The model is trained on thousands of examples where a user asks a question, and the expected assistant output is a perfectly formatted JSON tool call.'],
    ['Execution Loop', 'The model pauses generation when a tool call is made, waits for the system to append the tool response, and resumes generation.']
  ]}
/>

</ConceptTemplate>
`,
  '28. Large Language Models/Structured outputs/index.mdx': `---
title: Structured Outputs
description: Forcing LLMs to generate text that strictly adheres to a predefined mathematical schema like JSON.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Structured Outputs">

When integrating LLMs into software pipelines, relying on the model to "hopefully" output valid JSON is a catastrophic point of failure. The model might add conversational filler (e.g., "Here is your JSON:") or hallucinate invalid keys, crashing the downstream application.

Structured Outputs enforce strict mathematical guarantees that the LLM\\'s output will perfectly match a provided schema (like a Pydantic model or JSON Schema).

<Callout icon="tip" title="Constrained Decoding">
  Modern engines achieve 100% reliability using **Constrained Decoding**. During generation, the engine calculates the allowed next tokens based on a Finite State Machine derived from the JSON Schema. If the schema requires a boolean, the engine mathematically forces the probability of the word "true" or "false" to 100%, and masks out all other tokens in the vocabulary.
</Callout>

## Implementation Strategies

<ComparisonTable 
  headers={['Strategy', 'Reliability', 'Mechanism']}
  rows={[
    ['Prompt Engineering', 'Low', 'Telling the model "You must output valid JSON. Do not include markdown." It often disobeys.'],
    ['JSON Mode', 'Medium', 'The inference engine forces the output to be valid JSON, but cannot guarantee it matches your specific schema keys.'],
    ['Constrained Decoding (Structured Outputs)', '100% Guaranteed', 'The token probabilities are mathematically masked at the logits level using a Grammar or Finite State Machine to perfectly follow the schema.']
  ]}
/>

</ConceptTemplate>
`,
}

async function generateMega58() {
  for (const [relativePath, content] of Object.entries(contentMap)) {
    const fullPath = path.join(ROUTE_DIR, relativePath)
    await fs.mkdir(path.dirname(fullPath), { recursive: true })
    await fs.writeFile(fullPath, content, 'utf-8')
    console.log(`Generated thorough content for ${relativePath}`)
  }
}

generateMega58().catch(console.error)
