import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const PROJECT_ROOT = path.resolve(__dirname, '..')
const ROUTE_DIR = path.join(PROJECT_ROOT, 'src', 'features', 'kb', 'routes', 'KB')

const contentMap = {
  '48. Robotics/Kinematics (forward-inverse)/index.mdx': `---
title: Kinematics (Forward & Inverse)
description: The branch of classical mechanics that describes the motion of points, bodies, and systems of bodies without considering the forces that cause them to move.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Kinematics (Forward & Inverse)">

In Robotics, **Kinematics** is the pure geometry of motion. It answers the question: *"If I bend the robot's elbow by 30 degrees, exactly where is the robot's hand in 3D space?"*

Kinematics completely ignores gravity, weight, and force. It is strictly mathematical trigonometry and matrix algebra.

<Callout icon="info" title="Forward Kinematics">
  **Input:** Joint Angles ($\theta_1, \theta_2, \theta_3$)  
  **Output:** XYZ Coordinate of the Hand (End Effector)
  
  Forward Kinematics is mathematically trivial. If you know the length of the bicep, the length of the forearm, and the exact angles of the shoulder and elbow motors, you can easily use basic Trigonometry (Sine and Cosine) to calculate exactly where the hand is in 3D space.
</Callout>

## Inverse Kinematics (IK)

**Input:** XYZ Coordinate of the Hand  
**Output:** Joint Angles ($\theta_1, \theta_2, \theta_3$)

Inverse Kinematics is mathematically brutally difficult. If you tell a robotic arm, *"Move your hand to XYZ coordinate (10, 5, 2)"*, the robot must mathematically calculate exactly what angles to set its shoulder, elbow, and wrist to reach that point.

Often, there are **infinite mathematical solutions** (e.g., your human hand can stay in the exact same XYZ position in space while your elbow flaps up and down). IK is usually solved using complex Jacobian matrices or iterative gradient descent algorithms.

</ConceptTemplate>
`,
  '48. Robotics/Dynamics/index.mdx': `---
title: Robotic Dynamics
description: The study of forces and torques and their effect on motion, as opposed to kinematics, which studies the motion of objects without reference to its causes.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Robotic Dynamics">

If Kinematics is the pure geometry of movement, **Dynamics** is the brutal reality of physics. 

Dynamics answers the question: *"Exactly how much electrical torque must the shoulder motor output to lift a 10-pound weight if gravity is pulling it down?"*

<Callout icon="warning" title="The Nonlinear Nightmare">
  Robotic Dynamics is mathematically terrifying because it is highly nonlinear. 
  
  If the robot is swinging its arm fast, the centrifugal force mathematically pulls the arm outward. The Coriolis force twists the arm sideways. The elbow motor must continuously mathematically calculate and counteract the momentum generated by the shoulder motor, or the entire arm will swing wildly out of control.
</Callout>

## Forward vs Inverse Dynamics

- **Forward Dynamics:** (Simulation). Given the torque applied to the motors, what will be the resulting acceleration and movement of the robot?
- **Inverse Dynamics:** (Control). Given the desired acceleration and movement, exactly how much torque must be applied to the motors right now to achieve it, counteracting gravity and friction?

Engineers mathematically solve Dynamics using the **Newton-Euler equations** or the **Lagrangian mechanics** formulation, which calculates the difference between kinetic and potential energy in the system.

</ConceptTemplate>
`,
  '48. Robotics/Control systems/index.mdx': `---
title: Control Systems (PID)
description: A system of devices or set of devices, that manages, commands, directs or regulates the behavior of other devices or systems to achieve a desired result.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Control Systems (PID)">

If you command a drone to fly exactly 10 meters in the air, you cannot just turn the motors on to 100% and hope it stops perfectly at 10 meters. Momentum will carry it to 12 meters, gravity will pull it back down, and it will violently bounce in the air until it crashes.

To make physical machines move smoothly, we use **Control Theory**.

<Callout icon="success" title="The PID Controller">
  The absolute king of industrial control is the **PID Controller** (Proportional, Integral, Derivative). It constantly mathematically calculates the **Error** (the difference between where the drone is, and where it should be).
  
  - **Proportional (P):** The current error. (If you are far away, push the motors hard. If you are close, push gently).
  - **Integral (I):** The past error. (If the drone is stuck at 9.9 meters because the wind is pushing it down, the 'I' mathematically accumulates over time and gives an extra boost to overcome the wind).
  - **Derivative (D):** The future error. (If the drone is approaching 10 meters too fast, the 'D' recognizes the high velocity and mathematically slams the brakes to prevent overshooting).
</Callout>

## Tuning

Writing a PID controller in C takes exactly 5 lines of code. **Tuning** a PID controller (finding the perfect mathematical multipliers for P, I, and D) is a dark art that takes engineers weeks of trial and error.

</ConceptTemplate>
`,
  '48. Robotics/Actuators/index.mdx': `---
title: Robotic Actuators
description: The mechanical components responsible for moving and controlling a mechanism or system, requiring a control signal and a source of energy.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Robotic Actuators">

In general IoT, an actuator might just be a relay that turns on a lightbulb. In Robotics, **Actuators** are the high-performance physical muscles of the machine.

<Callout icon="info" title="The BLDC Revolution">
  Historically, robots used heavy, slow brushed DC motors with massive gearboxes. 
  
  Today, high-end robotics (like Boston Dynamics' Atlas or Tesla's Optimus) use **Brushless DC (BLDC) Motors**. BLDC motors have no physical brushes rubbing against the axle. They use massive, mathematically timed electromagnetic coils to pull permanent magnets. They are incredibly powerful, incredibly fast, and do not wear out mechanically.
</Callout>

## Types of Robotic Muscles

1. **Servo Motors:** A small DC motor bundled with a tiny internal PID controller and a potentiometer. You send it a digital signal ("Go to 90 degrees") and it handles the physics automatically. Heavily used in robotic arms and steering.
2. **Stepper Motors:** Motors that move in exact mathematical "steps" (e.g., 1.8 degrees per pulse). They do not need feedback sensors because you mathematically know exactly how many steps you commanded. Heavily used in 3D printers and CNC machines.
3. **Pneumatics/Hydraulics:** Using compressed air or pressurized oil to move physical pistons. Capable of mathematically terrifying amounts of raw force (lifting cars), but they require massive, leaky air compressors.

</ConceptTemplate>
`,
  '48. Robotics/Sensors/index.mdx': `---
title: Robotic Sensors (Proprioception vs Exteroception)
description: Devices that estimate a robot's condition and environment, allowing it to perceive its physical surroundings.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Robotic Sensors">

A robot must mathematically understand two completely different physical realities: 
1. Where is the world? 
2. Where are my own legs?

<Callout icon="tip" title="Proprioception (Self-Awareness)">
  Humans mathematically know where their arms are, even with their eyes closed. Robots achieve this using **Proprioceptive Sensors**.
  - **Encoders:** Optical discs attached to the motors that mathematically count exact degrees of rotation, allowing the robot to know its exact joint angles.
  - **IMU (Inertial Measurement Unit):** Accelerometers and Gyroscopes that mathematically tell the robot if it is currently falling over, allowing it to balance.
</Callout>

## Exteroception (World-Awareness)

To navigate the world without hitting a wall, robots use **Exteroceptive Sensors**.
- **LiDAR (Light Detection and Ranging):** A spinning laser that shoots millions of light pulses per second, mathematically measuring the exact time-of-flight of the photons bouncing back to generate a perfect 3D point-cloud of the room.
- **Ultrasonic / Sonar:** Shooting sound waves and measuring the echo. Cheap, but mathematically fuzzy.
- **Stereo Cameras:** Using two cameras (like human eyes) to mathematically calculate depth perception based on pixel offset.

</ConceptTemplate>
`,
  '48. Robotics/Computer vision for robotics/index.mdx': `---
title: Computer Vision for Robotics
description: The field of computer science that focuses on replicating parts of the complexity of the human vision system to enable robots to identify and process objects in images.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Computer Vision for Robotics">

A camera is just a massive 2D array of RGB numbers. **Computer Vision (CV)** is the mathematical process of turning that array of numbers into physical meaning (e.g., "That is a coffee cup at XYZ coordinate (2, 4, 1)").

<Callout icon="warning" title="The Real-Time Constraint">
  If you are tagging photos on Facebook, the CV algorithm can take 3 seconds to run. In robotics, if a drone is flying at 60 mph through a forest, the CV algorithm must mathematically process 60 frames per second. If it takes longer than 16 milliseconds to find the tree, the drone crashes.
</Callout>

## Classical CV vs Deep Learning

- **Classical CV (OpenCV):** Uses raw mathematical matrix operations. For example, a Canny Edge Detector mathematically looks for sudden, massive differences in pixel brightness to draw lines. Fast, but fragile if the lighting changes.
- **Deep Learning (YOLO / CNNs):** Uses Convolutional Neural Networks to identify objects. You feed the network 100,000 pictures of a coffee cup. The robot mathematically learns what a cup looks like regardless of lighting or angle. Much more robust, but requires massive GPU computing power on the robot (Edge AI).

</ConceptTemplate>
`,
  '48. Robotics/SLAM/index.mdx': `---
title: SLAM (Simultaneous Localization and Mapping)
description: The computational problem of constructing or updating a map of an unknown environment while simultaneously keeping track of an agent's location within it.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="SLAM (Simultaneous Localization and Mapping)">

If you drop a Roomba vacuum in a brand new house, it faces a massive mathematical paradox:
1. To know where it is, it needs a Map.
2. To build a Map, it needs to know exactly where it is.

Solving this paradox is called **SLAM**. It is arguably the most famous and mathematically difficult problem in modern robotics.

<Callout icon="error" title="The Odometry Drift Problem">
  Why can't the robot just count its wheel rotations (Odometry) to know where it is? 
  Because wheels slip. If the robot's wheels slip on a rug by just 1 millimeter, that mathematical error accumulates. After 10 minutes of driving, the robot mathematically believes it is in the kitchen, but it is physically crashing into the living room wall.
</Callout>

## The SLAM Solution

SLAM algorithms (like Gmapping or Cartographer) solve this using probabilistic mathematics (Particle Filters or Graph Optimization). 

As the robot drives, its LiDAR scans the walls. It mathematically aligns the *current* LiDAR scan with the *previous* LiDAR scan to correct the wheel slip. Slowly, it builds a massive 2D or 3D grid mathematically proving both the shape of the room and the robot's exact XY coordinate within that room.

</ConceptTemplate>
`,
  '48. Robotics/Path planning/index.mdx': `---
title: Path Planning (A* and RRT)
description: A computational problem to find a sequence of valid configurations that moves the object from the source to destination.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Path Planning">

Once SLAM has successfully built a map of the room, and the robot knows it is at Coordinate A, how does it physically navigate to Coordinate B without hitting the couch?

This is the mathematical domain of **Path Planning**.

<Callout icon="success" title="Grid-Based Planning (A*)">
  If the map is a 2D grid, the most famous algorithm is **A* (A-Star)**. 
  It mathematically explores the grid by calculating two numbers for every tile:
  1. \`g(n)\`: The exact cost to travel from the Start to this tile.
  2. \`h(n)\`: A mathematical heuristic (guess) of the straight-line distance from this tile to the Goal.
  
  A* is guaranteed to find the absolute shortest path, but if the map is massive (e.g., a 10,000x10,000 grid), the math takes too long to compute.
</Callout>

## Sampling-Based Planning (RRT)

If a robotic arm has 6 joints, its "Map" is a 6-Dimensional mathematical space. A* completely fails in 6D space because there are billions of tiles.

Instead, robots use **RRT (Rapidly-exploring Random Trees)**. The algorithm mathematically throws random darts into the 6D space. It connects the valid darts together like branches on a tree until one branch accidentally hits the Goal. It does not find the *perfect* path, but it finds a *valid* path incredibly fast.

</ConceptTemplate>
`,
  '48. Robotics/Motion planning/index.mdx': `---
title: Motion Planning & Trajectory Generation
description: The process of breaking down a desired movement task into discrete motions that satisfy movement constraints and possibly optimize some aspect of the movement.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Motion Planning & Trajectory Generation">

**Path Planning** mathematically draws a line on a map from Point A to Point B. But a line is just geometry. 

**Motion Planning** takes that line and adds Time, Velocity, and Acceleration constraints. It answers the question: *"Exactly how fast should the wheels spin at millisecond 400 to follow this line without the robot physically tipping over?"*

<Callout icon="tip" title="The Jerk Constraint">
  In physics, the derivative of Acceleration is called **Jerk**. 
  
  If a robot accelerates instantly from 0 to 10 mph, the Jerk is mathematically infinite. The robot's physical gears will violently grind and snap. Motion Planning algorithms mathematically generate smooth "S-Curve" velocity profiles to ensure that Acceleration ramps up slowly, keeping Jerk physically manageable.
</Callout>

## Obstacle Avoidance (Local Planning)

The global path plan says "Go down the hallway." But suddenly, a human steps into the hallway. 

The Local Motion Planner (like the **Dynamic Window Approach - DWA**) constantly runs at 20 Hz. It mathematically simulates 50 different arc-shaped trajectories the robot could drive in the next 1 second. It scores each trajectory (Penalizing driving near the human, rewarding driving toward the hallway goal), picks the best mathematical score, and executes it.

</ConceptTemplate>
`,
  '48. Robotics/Autonomous navigation/index.mdx': `---
title: Autonomous Navigation Stacks
description: The complete software architecture required to allow a robot to move through an environment without human intervention.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Autonomous Navigation">

**Autonomous Navigation** is not a single algorithm. It is the massive mathematical orchestration of everything discussed in this domain. 

To build a self-driving car or a warehouse delivery robot, engineers do not write one massive C++ file. They build a **Navigation Stack**.

<Callout icon="info" title="The Mathematical Pipeline">
  1. **Perception:** LiDAR and Cameras read the physical universe (Hardware).
  2. **Localization (SLAM/AMCL):** Matches the LiDAR to the Map to find the robot's XYZ coordinate.
  3. **Global Path Planner (A*):** Draws the 10-mile line from Start to Destination.
  4. **Local Trajectory Planner (DWA):** Calculates the exact steering angles for the next 2 seconds to dodge pedestrians.
  5. **Controller (PID):** Mathematically commands the physical voltage to the steering motors.
</Callout>

## Sensor Fusion

Because no sensor is perfect (LiDAR fails in fog, Cameras fail in darkness, Odometry slips on ice), the Navigation Stack uses **Sensor Fusion**.

Using an advanced mathematical algorithm called a **Kalman Filter**, the robot takes 5 different noisy, conflicting sensor inputs and mathematically calculates the statistical probability of its true state, resulting in a single, highly accurate truth.

</ConceptTemplate>
`,
}

async function generateMega87() {
  for (const [relativePath, content] of Object.entries(contentMap)) {
    const fullPath = path.join(ROUTE_DIR, relativePath)
    await fs.mkdir(path.dirname(fullPath), { recursive: true })
    await fs.writeFile(fullPath, content, 'utf-8')
    console.log(`Generated thorough content for ${relativePath}`)
  }
}

generateMega87().catch(console.error)
