import fs from 'fs/promises'
import path from 'path'

const TICK3 = '```'
const TICK1 = '`'

const contentMap = {
  'src/features/kb/routes/KB/34. MLOps & LLMOps/Experiment tracking/index.mdx': `---
title: Experiment Tracking
description: The rigorous scientific MLOps practice of mathematically logging every single hyperparameter, dataset hash, and loss metric during thousands of neural network training runs to ensure reproducibility.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Experiment Tracking">

Training a Neural Network is not writing code; it is conducting a massive mathematical experiment. If you train 50 models, and Model #42 was the best, but you forgot what Learning Rate you used for Model #42, the experiment is a total failure.

## 1. The Metric Logs
Experiment Tracking tools (like MLflow or Weights & Biases) run as background daemons during training.
Every time the Neural Network completes an Epoch, the script mathematically pushes the exact Training Loss, Validation Loss, and Accuracy to the tracker. The tracker automatically plots these mathematical trajectories on a dashboard. You can instantly see if a model is mathematically diverging (Loss exploding to infinity) and kill the GPU instance to save money.

## 2. The Artifact Bindings
A logged metric is useless without context.
When an experiment finishes, the tracking tool mathematically binds exactly three things together in a single immutable record:
1. The **Hyperparameters** (e.g., Learning Rate = 0.001, Batch Size = 32).
2. The **Dataset Hash** (the exact DVC pointer to the data used).
3. The **Artifacts** (the raw TICK1.ptTICK1 model weights generated by the run).
This guarantees absolute scientific reproducibility. Years later, an engineer can look at Run #42 and mathematically recreate it byte-for-byte.

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/34. MLOps & LLMOps/Feature stores/index.mdx': `---
title: Feature Stores
description: A centralized, high-performance data engineering layer in MLOps that calculates, mathematically transforms, and serves Machine Learning features to guarantee absolute consistency between training and production.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Feature Stores">

A Data Scientist calculates a feature in a Jupyter Notebook: *"User's average spend over 30 days."* Six months later, a Software Engineer tries to rewrite that exact mathematical logic in Java for the production API. The math is slightly different. The model silently fails. This is Training-Serving Skew.

## 1. The Single Source of Mathematical Truth
A Feature Store (like Feast or Hopsworks) solves this by decoupling the Feature Math from the Model.
The Data Engineer writes the mathematical transformation *once* and registers it to the Feature Store. 
- **Offline Store (Training)**: The Feature Store uses a massive Data Warehouse (like Snowflake) to run batch processing, generating millions of historical rows of the feature so the Data Scientist can train the Neural Network.
- **Online Store (Serving)**: The Feature Store simultaneously syncs that exact same mathematical logic to a low-latency database (like Redis).

## 2. Preventing Training-Serving Skew
When the API receives a live request (e.g., User ID 123 applies for a loan), the API does *not* calculate the "30-day average spend" itself. 
It queries the Online Feature Store, which returns the exact, pre-calculated float in 2 milliseconds. Because the Offline Store and the Online Store are physically powered by the exact same mathematical definition, Training-Serving Skew is mathematically eliminated.

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/34. MLOps & LLMOps/Kubeflow/index.mdx': `---
title: Kubeflow
description: The industry-standard, Kubernetes-native MLOps platform designed to orchestrate massive, mathematically complex Machine Learning pipelines, from data preprocessing to hyperparameter tuning and model serving.
---
import { TechnologyTemplate } from '@/features/kb/components/templates/TechnologyTemplate'

<TechnologyTemplate
  title="Kubeflow"
  subtitle="The Kubernetes Machine Learning OS"
  tags={['MLOps', 'Kubernetes', 'Pipelines', 'Scaling']}
>

Machine Learning is mathematically too massive for a single laptop. It requires distributed computing. Kubeflow is the operating system that forces Kubernetes to understand the specific architectural needs of Neural Networks.

## 1. Kubeflow Pipelines (KFP)
Training a model is a Directed Acyclic Graph (DAG) of mathematical steps. 
In Kubeflow, you define the DAG in Python. (e.g., Step A: Extract Data -> Step B: Normalize Tensors -> Step C: Train ResNet50).
Kubeflow mathematically converts this Python code into a Kubernetes YAML file. When executed, Kubeflow spins up an independent Docker container for every single step. If Step C (Training) requires 8 GPUs, Kubeflow dynamically allocates 8 GPUs specifically for that container, runs the math, saves the output tensor to cloud storage, and immediately kills the GPUs to save money.

## 2. Katib (Hyperparameter Tuning)
Finding the perfect Learning Rate is a mathematical nightmare of trial and error. 
Kubeflow includes **Katib**, a distributed Hyperparameter tuning engine. You give Katib a mathematical search space (e.g., $0.0001 < LR < 0.1$). Katib spins up 50 parallel Kubernetes pods, trains 50 different neural networks simultaneously using Bayesian Optimization algorithms, mathematically compares their Validation Loss, and returns the absolute optimal Hyperparameter configuration.

</TechnologyTemplate>
`,

  'src/features/kb/routes/KB/34. MLOps & LLMOps/Langfuse)/index.mdx': `---
title: Langfuse
description: An advanced open-source LLMOps observability platform that mathematically traces the complex execution graphs, latency bottlenecks, and token economics of multi-step Generative AI applications.
---
import { TechnologyTemplate } from '@/features/kb/components/templates/TechnologyTemplate'

<TechnologyTemplate
  title="Langfuse"
  subtitle="Open Source LLM Observability"
  tags={['LLMOps', 'Observability', 'Tracing', 'Metrics']}
>

When a user interacts with a modern AI Agent, the system does not make one LLM call. It runs a complex mathematical graph: Extract intent, search a vector database, summarize context, and generate a final response. If it takes 15 seconds and outputs garbage, you need to know exactly which node in the graph failed.

## 1. Distributed Execution Tracing
Langfuse instruments your code to capture **Distributed Traces**.
Every single action (an LLM call, a database query, a Python function) is logged as a mathematical **Span**. Langfuse visually reconstructs the entire execution DAG.
You can instantly see the exact mathematical breakdown:
- The Vector Search took 200ms.
- The LLM summarization took 12 seconds.
- The exact prompt sent to the LLM was 4,200 tokens long.
This allows engineers to surgically optimize the mathematical bottlenecks in the chain.

## 2. Token Economics and User Feedback
Because Langfuse traces every LLM call, it precisely calculates the mathematical cost of every single user interaction based on the API pricing (e.g., this exact conversation cost $0.043). 
Furthermore, it ties the final Trace to human feedback. If a user clicks a "Thumbs Down" on the UI, Langfuse mathematically flags the entire Execution Trace, allowing engineers to see the exact context, prompt, and intermediate steps that led the LLM to hallucinate.

</TechnologyTemplate>
`,

  'src/features/kb/routes/KB/34. MLOps & LLMOps/LLM evaluation pipelines/index.mdx': `---
title: LLM Evaluation Pipelines
description: The rigorous LLMOps methodology of mathematically scoring the subjective, generative text outputs of Large Language Models against standardized datasets to measure alignment, accuracy, and hallucination rates.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="LLM Evaluation Pipelines">

In traditional ML, evaluating a model is easy: if it predicts 1 and the answer is 1, the math is correct. In LLMs, the model predicts a paragraph of text. Mathematically scoring a paragraph is incredibly difficult.

## 1. Static Benchmarks vs. Golden Datasets
To know if an LLM update broke the system, you must run it through a Pipeline.
- **Static Benchmarks (MMLU, HumanEval)**: Standardized academic tests. Useful for foundational models, but useless for business applications.
- **Golden Datasets**: MLOps teams curate 1,000 highly specific, perfect Q&A pairs (e.g., 1,000 exact legal questions and their perfect legal answers). Every time the Prompt or the LLM is updated, the Pipeline mathematically forces the LLM to answer all 1,000 questions.

## 2. LLM-as-a-Judge
How do you grade the 1,000 answers? Human grading takes weeks.
The industry standard is **LLM-as-a-Judge**. The Pipeline takes the Model's Answer, the Golden Answer, and feeds both into a massive, highly capable model (like GPT-4). 
GPT-4 is mathematically instructed: *"Score the Model's Answer from 1 to 5 based on its factual alignment with the Golden Answer. Ignore stylistic differences."* 
This automated mathematical scoring allows engineers to rapidly iterate on prompts and RAG architectures, getting a quantified score of the system's accuracy in minutes instead of months.

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/34. MLOps & LLMOps/LLM observability (LangSmith/index.mdx': `---
title: LangSmith (LLM Observability)
description: A premier LLMOps tracing and evaluation platform built by LangChain, designed to deeply inspect the internal mathematical state, token usage, and execution logic of complex Agentic AI workflows.
---
import { TechnologyTemplate } from '@/features/kb/components/templates/TechnologyTemplate'

<TechnologyTemplate
  title="LangSmith"
  subtitle="Deep Tracing for AI Agents"
  tags={['LLMOps', 'LangChain', 'Tracing', 'Evaluation']}
>

Building a simple LLM wrapper is easy. Building a complex, multi-agent RAG system with LangChain is a debugging nightmare. When the Agent goes into an infinite loop or retrieves the wrong document, print statements are mathematically insufficient.

## 1. Native LangChain Integration
LangSmith is deeply integrated into the mathematical architecture of LangChain. 
With a single environment variable, it recursively traces every component in the chain. If an Agent uses a Tool (like a Calculator or a Web Search), LangSmith logs the exact input parameters the Agent generated, the exact mathematical output of the Tool, and how the Agent incorporated that data into its next prompt. This provides total transparency into the "thought process" of the ReAct (Reasoning and Acting) loop.

## 2. Continuous Dataset Evaluation
LangSmith is not just for debugging; it is for mathematical iteration.
If you find a Trace where the Agent failed, you can click a button to add that exact Trace to a **Testing Dataset**. Over time, you build a massive dataset of edge cases.
When you update the System Prompt, you can mathematically execute the new prompt against the entire Dataset directly inside LangSmith, comparing the new outputs against the old outputs side-by-side to ensure you did not introduce regression errors.

</TechnologyTemplate>
`,

  'src/features/kb/routes/KB/34. MLOps & LLMOps/MLflow/index.mdx': `---
title: MLflow
description: The de facto standard open-source platform for managing the end-to-end Machine Learning lifecycle, unifying experiment tracking, model registry, and mathematically reproducible deployment pipelines.
---
import { TechnologyTemplate } from '@/features/kb/components/templates/TechnologyTemplate'

<TechnologyTemplate
  title="MLflow"
  subtitle="The End-to-End MLOps Platform"
  tags={['MLOps', 'Tracking', 'Registry', 'Python']}
>

Developed by Databricks, MLflow is the glue that holds MLOps together. It mathematically guarantees that a model trained on a laptop can be reproduced, tracked, and deployed to a cloud cluster without losing a single piece of metadata.

## 1. The MLflow Tracking Server
MLflow replaces chaotic spreadsheets with a centralized API. 
When training code runs, it calls TICK1mlflow.log_metric("loss", 0.1)TICK1. The tracking server mathematically stores the hyperparameters, the Git commit hash of the code, and the loss curves. 
Most importantly, it logs the **Environment**. MLflow automatically captures the exact mathematical versions of PyTorch, CUDA, and Pandas, ensuring that the model can be deserialized perfectly years later.

## 2. The Model Registry and Flavors
Once an experiment is deemed successful, it is pushed to the **MLflow Model Registry**, which acts as a mathematical CI/CD pipeline for AI (Staging $\\rightarrow$ Production $\\rightarrow$ Archived).
MLflow solves deployment friction using **Flavors**. A Scikit-Learn model is mathematically different from a PyTorch model. MLflow wraps them all in a standardized TICK1MLmodelTICK1 format. A DevOps engineer does not need to know PyTorch to deploy the model; they just point the deployment server at the MLflow Flavor, and MLflow automatically loads the exact mathematical dependencies required to run the inference.

</TechnologyTemplate>
`,

  'src/features/kb/routes/KB/34. MLOps & LLMOps/Model monitoring/index.mdx': `---
title: Model Monitoring
description: The continuous, automated MLOps practice of mathematically analyzing the real-time statistical distributions of live API predictions to detect silent degradation, bias, and drift before they impact users.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Model Monitoring">

Unlike traditional software, an ML model does not throw a 500 Server Error when it breaks. It just confidently returns a bad mathematical prediction. Model Monitoring is the immune system that detects this silent failure.

## 1. Statistical Baselines
A Model Monitoring system (like Evidently AI or Arize) cannot function without a mathematical baseline. 
During training, the MLOps pipeline calculates the exact statistical distribution (mean, variance) of every single input feature (e.g., Age) and the output prediction (e.g., Loan Approval Rate = 15%). This is the **Reference Data**.
In production, the system continuously calculates the exact same mathematical distributions on the live API traffic (the **Live Data**). 

## 2. Anomaly Detection and Alerts
The monitoring system mathematically compares the Live Data to the Reference Data using statistical tests (like Population Stability Index or Kullback-Leibler Divergence).
- **Output Drift**: If the model suddenly starts approving 60% of loans instead of the baseline 15%, the system fires a critical alert. 
- **Data Quality Alerts**: If the API starts receiving "Age = null" or "Age = -5" because an upstream database broke, the neural network will mathematically output garbage. The monitor intercepts these anomalies, alerting data engineers to fix the pipeline before the model poisons the business logic.

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/34. MLOps & LLMOps/Model registries/index.mdx': `---
title: Model Registries
description: The central, version-controlled MLOps repository that mathematically stores, tags, and governs the lifecycle state of trained Machine Learning models as they transition from experimentation to production.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Model Registries">

A Model Registry is the Git Repository for compiled Neural Networks. You do not deploy a model by emailing a TICK1.ptTICK1 file. You push it to a Registry, which cryptographically secures it and manages its deployment state.

## 1. Lifecycle Governance
A Registry (like MLflow Model Registry or AWS SageMaker Registry) defines strict mathematical boundaries for models. 
When a model is uploaded, it is versioned (e.g., TICK1FraudNet-v14TICK1) and placed in a specific **State**:
- **Staging**: The model is locked in a test environment, undergoing mathematical shadow-testing and security audits.
- **Production**: The model is actively serving live API traffic.
- **Archived**: The model is deprecated but cryptographically retained for legal compliance and rollback capability.
By forcing all models through this lifecycle, the Registry prevents a Data Scientist from accidentally deploying untested experimental weights directly to live servers.

## 2. Dependency and Lineage Tracking
A raw model file is mathematically dangerous without its lineage. 
The Registry strictly binds the model to its metadata. If you inspect TICK1FraudNet-v14TICK1 in the Registry, it will tell you exactly which Git commit trained it, the exact SHA-256 hash of the DVC dataset used, and the exact Python library versions required to run it. This mathematical lineage is legally required in many industries (like finance and healthcare) to prove exactly how and why a model was built.

</ConceptTemplate>
`,

  'src/features/kb/routes/KB/34. MLOps & LLMOps/Model serving/index.mdx': `---
title: Model Serving
description: The highly specialized MLOps infrastructure layer responsible for loading raw mathematical model weights into VRAM and exposing them as secure, high-throughput, low-latency APIs.
---
import { ConceptTemplate } from '@/features/kb/components/templates/ConceptTemplate'

<ConceptTemplate title="Model Serving">

A Jupyter Notebook mathematically processes one image in a second. A global API must mathematically process 5,000 images a second. Model Serving is the DevOps engineering required to bridge that gap.

## 1. The Serving Architecture
Model Serving engines (like NVIDIA Triton, TorchServe, or BentoML) are fundamentally different from standard web servers (like Nginx).
- **VRAM Management**: They mathematically optimize the loading of 10GB neural network weights directly into GPU memory, ensuring multiple models can share a single GPU without causing Out-of-Memory (OOM) crashes.
- **Dynamic Batching**: If 100 users hit the API in the same millisecond, a standard web server processes them sequentially. A Model Serving engine intercepts the 100 requests, mathematically fuses them into a single $100 \\times N$ Tensor, executes a single hardware-accelerated pass on the GPU, and splits the results back to the users. This increases throughput by orders of magnitude.

## 2. Serverless vs. Dedicated Endpoints
- **Serverless Inference**: The model is spun down to zero when unused. When a request hits, the infrastructure boots up the container, loads the weights, and runs the math. Excellent for saving money, but mathematically suffers from "Cold Start" latency (taking 5+ seconds to boot).
- **Dedicated Endpoints**: The model is permanently locked in GPU VRAM, mathematically ready to execute inference in sub-milliseconds, 24/7. Required for real-time systems (like self-driving cars or trading algorithms) where cold starts are fatal.

</ConceptTemplate>
`
}

async function main() {
  for (const [filePath, content] of Object.entries(contentMap)) {
    const fullPath = path.resolve(filePath)
    await fs.mkdir(path.dirname(fullPath), { recursive: true })
    
    // Safely replace TICK1 and TICK3 placeholders with actual backticks
    let finalContent = content.replace(/TICK3/g, TICK3).replace(/TICK1/g, TICK1)
    
    // Append a safe newline
    await fs.writeFile(fullPath, finalContent.trim() + '\n', 'utf-8')
    console.log('Wrote ' + filePath)
  }
}

main().catch(console.error)
